[DEV-1799] refactor guests component
pagopa/developer-portal pull request #1012
Opened 2024-07-19 14:37 UTC by MarBert

#### List of Changes

Update webinar guest component and grid

#### Motivation and Context

The old webinar UI needed a refactor 

#### How Has This Been Tested?

On localhost 

#### Screenshots (if appropriate):
<img width="716" alt="image" src="https://github.com/user-attachments/assets/1cbfe579-1e26-42d4-8b4d-1dc80eaa9297">

<img width="242" alt="image" src="https://github.com/user-attachments/assets/57d28961-bdbd-4ad5-a9f6-196946601328">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-22 13:37 UTC, MarcoPonchia submitted a review, later dismissed
I see some differences from figma on webinar detail page. Mock show that Speakers component should fill content width, but now it only works with 4 speakers
![Screenshot from 2024-07-22 15-30-15](https://github.com/user-attachments/assets/980d7047-bd55-4cc7-8792-0e686e931448)
![Screenshot from 2024-07-22 15-30-25](https://github.com/user-attachments/assets/1f811000-0bca-47fa-9c9b-3d7848178eef)

Speakers component does not show description in webinar detail page on mobile

2024-07-23 08:08 UTC, tommaso1 requested changes

2024-07-23 08:08 UTC, tommaso1 commented on apps/nextjs-website/src/components/molecules/SpeakerPreview/SpeakerPreview.tsx
> +        flexDirection: { sm: 'row', md: flexDirection },
you could use a space-between with an inner div with row to have the items aligned as the figma file

2024-07-24 09:02 UTC, marcobottaro requested changes

2024-07-24 17:22 UTC, marcobottaro approved these changes

2024-07-24 18:12 UTC, merged