[CAI-90] New Chatbot Messages
pagopa/developer-portal pull request #1037
Opened 2024-08-01 15:55 UTC by Sebastiano-Bertolin

#### List of Changes
New Chatbot Messages

#### Motivation and Context
Update style as per mockup

#### How Has This Been Tested?
Manually via storybook and in nextjs

#### Screenshots (if appropriate):
<img width="1155" alt="Screenshot 2024-08-01 at 17 55 53" src="https://github.com/user-attachments/assets/613e4ca0-61e1-4b57-a9d8-ad0e8298d05c">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-06 14:36 UTC, MarcoPonchia requested changes

2024-08-06 15:55 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/ChatMessage/ChatMessage.tsx
![image](https://github.com/user-attachments/assets/59135210-c355-4abb-9a70-4b4cb693d2fa)
I suggest you to add here a component to manage day/today label based on a new attribute like `showDayLabel` false by default that will be passed as true when `Query` are convert into message only if previus message is missing or in date day changes.

2024-08-08 09:26 UTC, Sebastiano-Bertolin commented on apps/nextjs-website/src/components/atoms/ChatMessage/ChatMessage.tsx
Done

2024-08-08 11:02 UTC, MarcoPonchia approved these changes

2024-08-20 15:44 UTC, closed without merging

2024-08-20 15:44 UTC, MarcoPonchia commented
Included in https://github.com/pagopa/developer-portal/pull/1046 that is already merged