[CAI-90] Update Chatbot Chat Component
pagopa/developer-portal pull request #1040
Opened 2024-08-02 15:08 UTC by Sebastiano-Bertolin

#### List of Changes
Update Chat component with new style and layout

#### Motivation and Context
Update style as per mockup

#### How Has This Been Tested?
Manually via Storybook and in Webapp

#### Screenshots (if appropriate):
![Screenshot 2024-08-02 at 17 07 57](https://github.com/user-attachments/assets/9778dfbf-a703-44d4-bf03-0d4606981dc3)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-08 14:39 UTC, MarcoPonchia requested changes

2024-08-08 14:42 UTC, MarcoPonchia requested changes

2024-08-08 14:42 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/ChatInputText/ChatInputText.tsx
there are some fixes that are applied [here](https://github.com/pagopa/developer-portal/pull/1044) that are not merged yet in this PR i think is better to merged all components pr to avoid conflict

2024-08-19 13:18 UTC, Sebastiano-Bertolin commented on apps/nextjs-website/src/components/atoms/ChatChatbotWriting/ChatChatbotWriting.tsx
> +          />
This suggestion does not work like as it's now

2024-08-20 15:44 UTC, MarcoPonchia commented
Included in https://github.com/pagopa/developer-portal/pull/1046 that is already merged

2024-08-20 15:44 UTC, closed without merging