[DEV-1860,DEV-1859] Add guides and guides list page on strapi
pagopa/developer-portal pull request #1042
Opened 2024-08-06 13:36 UTC by tommaso1

#### List of Changes

Add Guides and GuidesListPage models on strapi

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-06 15:32 UTC, MarcoPonchia requested changes

2024-08-06 15:32 UTC, MarcoPonchia commented on apps/strapi-cms/src/components/common/guide-section.json
I think this file was push by error because seems unused, can be deleted

2024-08-06 15:32 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/guide/content-types/guide/schema.json
> +      "repeatable": false,
```suggestion
      "repeatable": true,
```
In `apps/strapi-cms/src/api/guide/content-types/guide/lifecycles.ts` for this attribute should also be cheked that listItem is an Array of max 4 element. I check but unfortunately strapi does not permit to set it from component setting.

2024-08-19 09:23 UTC, marcobottaro requested changes
You should add the changeset file

2024-08-19 13:48 UTC, MarcoPonchia approved these changes

2024-08-19 13:49 UTC, marcobottaro approved these changes

2024-08-19 13:49 UTC, merged