[CAI-106] Add skeleton for chatbot
pagopa/developer-portal pull request #1048
Opened 2024-08-08 16:00 UTC by MarcoPonchia

#### List of Changes

Add chat skeleton

#### Motivation and Context

Show skeleton while chatbot info are loaded

#### How Has This Been Tested?

Manually on storybook here: http://localhost:6006/?path=/story/organisms-chatbotlayout--loading-chat-session

#### Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/73e78a26-e2f6-42d0-8dfa-a955e139b165)

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-20 15:42 UTC, Sebastiano-Bertolin approved these changes

2024-08-21 10:39 UTC, marcobottaro requested changes

2024-08-21 10:39 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/Chat/Chat.tsx
> +          backgroundColor: 'white',
```suggestion
          backgroundColor: palette.background.paper,
```

2024-08-21 10:39 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/Chat/Chat.tsx
> +
I think you should replace `backgroundColor: 'white',` with `backgroundColor: palette.background.paper,` also on line 70

2024-08-21 12:03 UTC, marcobottaro approved these changes

2024-08-21 12:03 UTC, merged