Cai 126 update question and answers component
pagopa/developer-portal pull request #1056
Opened 2024-08-21 13:34 UTC by MarcoPonchia

#### List of Changes

Hide webinar questions instead of not render when collapsed

#### Motivation and Context

Hide webinar questions instead of not render when collapsed to make chatbot able to analize page

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-21 15:32 UTC, Sebastiano-Bertolin approved these changes

2024-08-22 10:24 UTC, marcobottaro requested changes

2024-08-22 10:24 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/QuestionsAndAnswers/QuestionsAndAnswers.tsx
> +            key={item.question}
```suggestion
            key={index}
```

2024-08-22 10:37 UTC, marcobottaro approved these changes

2024-08-22 10:48 UTC, merged