[DEV-1873] Seo plugin in homepage
pagopa/developer-portal pull request #1066
Opened 2024-08-27 19:35 UTC by tommaso1

The meta tags in home page are taken from strapi if present

#### List of Changes

This is a first implementation of using SEO plugin in next js app

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-29 12:20 UTC, MarcoPonchia submitted a review, later dismissed

2024-08-29 15:28 UTC, marcobottaro requested changes

2024-08-29 15:28 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/metadata.helpers.ts
> +export const makeMetadataFromStrapiCeoPlugin = (seo: SEO): Metadata => {
Do we really need `SeoPlugin` suffix in the constant name?
```suggestion
export const makeMetadataFromStrapi = (seo: SEO): Metadata => {
```

2024-08-29 16:25 UTC, marcobottaro requested changes

2024-08-29 16:25 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/metadata.helpers.ts
> +    image: seo.metaImage?.data?.attributes?.url,
You should add more properties if you want to use the preexistent `makeMetadata` function.
The home page should show the results of all of the SEO properties

2024-08-30 07:59 UTC, marcobottaro approved these changes

2024-08-30 08:17 UTC, merged