[DEV-1881] Add ckeditor to strapi tutorias
pagopa/developer-portal pull request #1088
Opened 2024-09-04 19:57 UTC by tommaso1

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-05 08:13 UTC, marcobottaro requested changes

2024-09-05 08:13 UTC, marcobottaro commented on .changeset/calm-wolves-shave.md
> +adds ckeditor to tutorials
```suggestion
Add CKEditor to Tutorials' parts
```

2024-09-09 13:37 UTC, marcobottaro approved these changes

2024-09-12 13:07 UTC, MarcoPonchia approved these changes

2024-09-12 13:17 UTC, merged