[DEV-1882] Rendering ck editor content on tutorials
pagopa/developer-portal pull request #1092
Opened 2024-09-05 10:38 UTC by tommaso1

#### List of Changes

Adds a basic renderer for ck editor content on tutorials page

#### Motivation and Context

Makes easier to create tutorial

#### How Has This Been Tested?

#### Screenshots (if appropriate):
<img width="986" alt="Screenshot 2024-09-05 at 12 31 27" src="https://github.com/user-attachments/assets/c424dbfa-1c80-4d16-be5a-4ee5490423c2">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-11 08:33 UTC, marcobottaro requested changes

2024-09-11 08:33 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/CkEditorPart/CkEditorPart.tsx
> +      <div dangerouslySetInnerHTML={{ __html: content }}></div>
Considering that the `content` comes from the backend, you should "sanitize" it.
Take a look at [DOMPurify](https://github.com/cure53/DOMPurify) and [Isomorphic DOMPurify](https://github.com/kkomelin/isomorphic-dompurify)

2024-09-11 08:33 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/CkEditorPart/CkEditorPart.tsx
> +    <Box className={'container'} sx={{}}>
```suggestion
    <Box className={'container'}>
```

2024-09-12 13:11 UTC, MarcoPonchia approved these changes

2024-09-13 07:29 UTC, marcobottaro requested changes

2024-09-13 07:29 UTC, marcobottaro commented on .changeset/calm-wolves-shave.md
I thin k you should remove this changeset

2024-09-13 07:49 UTC, marcobottaro approved these changes

2024-09-13 08:55 UTC, merged