[DEV-1900] Refactor product strapi
pagopa/developer-portal pull request #1094
Opened 2024-09-05 12:51 UTC by MarcoPonchia

#### List of Changes

Refactor Product in Strapi

#### Motivation and Context

Remove static products

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-05 13:43 UTC, marcobottaro approved these changes

2024-09-13 08:55 UTC, marcobottaro requested changes

2024-09-13 08:55 UTC, marcobottaro commented on package-lock.json
Remove this change

2024-09-25 08:46 UTC, marcobottaro approved these changes

2024-10-03 15:20 UTC, tommaso1 approved these changes

2024-10-04 07:48 UTC, merged