[DEV-1887] Add seo on all pages
pagopa/developer-portal pull request #1119
Opened 2024-09-12 10:07 UTC by tommaso1

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-17 08:57 UTC, MarcoPonchia requested changes

2024-09-17 08:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/codecs/ProductCodec.ts
> +import { SEOCodec } from './SeoCodec';
```suggestion
```

2024-09-17 08:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/codecs/ProductCodec.ts
> +      seo: t.union([NullToUndefinedCodec, SEOCodec]),
```suggestion
```

2024-09-17 08:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/__tests__/solutions.test.ts
> +              seo: null,
```suggestion
```

2024-09-17 08:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/__tests__/fixtures/solution.ts
> +import { setOption } from 'monocle-ts/lib/Optional';
```suggestion
```

2024-09-17 08:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/__tests__/fixtures/product.ts
> +      seo: null,
```suggestion
```

2024-09-17 09:51 UTC, MarcoPonchia requested changes

2024-09-17 09:51 UTC, MarcoPonchia commented on .changeset/green-moons-jog.md
I also will add a new changeset dedicated to the changes of this pr

2024-09-17 15:26 UTC, MarcoPonchia approved these changes

2024-09-24 12:28 UTC, marcobottaro approved these changes

2024-09-24 12:29 UTC, merged