[DEV-1951] Add urlreplacemap codec, + tests + mapping function
pagopa/developer-portal pull request #1166
Opened 2024-09-30 12:12 UTC by tommaso1

#### List of Changes

Adds the codec to read and parse urlreplacemap from strapi

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-03 07:42 UTC, MarBert submitted a review, later dismissed

2024-10-03 07:42 UTC, MarBert commented on .changeset/healthy-cobras-type.md
This is the changeset from DEV-1950. Shouldn't there be a changeset for DEV-1951 ?

2024-10-03 08:31 UTC, marcobottaro requested changes

2024-10-03 08:31 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/__tests__/urlReplaceMap.test.ts
> +                },
```suggestion
                image: mediaRasterJson,
```

2024-10-03 08:31 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/__tests__/urlReplaceMap.test.ts
> +                },
```suggestion
                mobileImage: mediaRasterJson,
```

2024-10-03 08:31 UTC, marcobottaro commented on .changeset/healthy-cobras-type.md
After the merge of the pull request DEV-1950 this file with all the changes in `strapi-cms/src` should desappear

2024-10-04 09:11 UTC, marcobottaro requested changes

2024-10-04 09:11 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/codecs/UrlReplaceMapCodec.ts
> +    data: GuideCodec,
```suggestion
    data: t.union([NullToUndefinedCodec, GuideCodec]),
```

2024-10-09 09:24 UTC, merged