[CAI-204] Chatbot/presidio in docker for local development
pagopa/developer-portal pull request #1201
Opened 2024-10-14 15:59 UTC by batdevis

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-22 15:35 UTC, mdciri requested changes

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/docker/app.local.Dockerfile
> +RUN python -m spacy download en_core_web_md
here are missing to download: `es_core_news_md`, `de_core_news_md`, `fr_core_news_md`,  `el_core_news_md`, `hr_core_news_md`, and `sl_core_news_md`.

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/pyproject.toml
> +presidio-analyzer = "^2.2.355"
remove `presidio-anonymizer` and `presidio-analyzer` and install `llama-index-postprocessor-presidio` as in the `pyproject.toml` in main. Check this out.

In the end, why `chromedriver-py`?

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/app/main.py
>  )
in boto3 session are missing the `aws_access_key_id` and `aws_secret_access_key`

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/app/main.py
> -  profile_name='dummy'
I saw this `dummy` in many files. isn't better to but this `profile_name` in `config/params.yaml` or in a enviroment variable?

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/app/main.py
> +  )
`aws_access_key_id` and `aws_secret_access_key` are missing

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/app/main.py
`aws_access_key_id` and `aws_secret_access_key` are missing

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/modules/utils.py
>          aws_access_key_id=AWS_ACCESS_KEY_ID,
`aws_access_key_id` and `aws_secret_access_key` are missing, but this is already handled in `main`

2024-10-22 15:35 UTC, mdciri commented on apps/chatbot/src/modules/vector_database.py
> +        if 6 == 9:
fix this

2024-10-30 09:27 UTC, closed without merging

2024-10-30 09:27 UTC, batdevis commented
now it works with Presidio