[DEV-1976] update onboarding doc
pagopa/developer-portal pull request #1235
Opened 2024-11-08 14:12 UTC by MarBert

#### List of Changes

Update the README.md to include some onboarding information

#### Motivation and Context

Some info were missing
#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-11-08 14:42 UTC, marcobottaro requested changes

2024-11-08 14:42 UTC, marcobottaro commented on README.md
> +      },
```suggestion
      pool: {
        min: 2,
        max: 20,
        acquireTimeoutMillis: 300000,
        createTimeoutMillis: 300000,
        destroyTimeoutMillis: 300000,
        idleTimeoutMillis: 30000,
        reapIntervalMillis:1000,
        createRetryIntervalMillis: 2000
      },
```

2024-11-08 14:47 UTC, marcobottaro requested changes

2024-11-08 14:47 UTC, marcobottaro commented on README.md
> +Give that SQLite is used for local developement, this transfer will require the following lines to be added to `apps/strapi-cms/config/database.ts`:
```suggestion
Give that SQLite is used for local developement, this transfer will require the following lines to be added to `apps/strapi-cms/config/database.ts` at the end of the `sqlite` object:
```

2024-11-08 14:48 UTC, marcobottaro approved these changes

2024-11-08 14:49 UTC, marcobottaro requested changes
You should add the changeset file (with 2 patches)

2024-11-08 14:54 UTC, marcobottaro approved these changes

2024-11-08 17:55 UTC, marcobottaro approved these changes

2024-11-11 09:09 UTC, christian-calabrese approved these changes

2024-11-11 09:17 UTC, merged