[DEV-2016] Connect cognito event to active campaign
pagopa/developer-portal pull request #1253
Opened 2024-11-21 17:57 UTC by MarcoPonchia

#### List of Changes

Connect cognito event to active campaign

#### Motivation and Context

Cognito User are sync in Active campaign 

#### How Has This Been Tested?

Add test and manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-11-26 09:45 UTC, tommaso1 approved these changes

2024-11-26 14:28 UTC, marcobottaro commented on packages/active-campaign-client/src/__tests__/helpers/deleteContact.test.ts
> +// remove .skip to run the test, be aware it does a real API call so it will create a contact in the active campaign account
```suggestion
// remove .skip to run the test, be aware it does a real API call so it will delete a contact in the active campaign account
```

2024-11-26 14:29 UTC, marcobottaro commented on packages/active-campaign-client/src/__tests__/helpers/updateContact.test.ts
> +// remove .skip to run the test, be aware it does a real API call so it will create a contact in the active campaign account
```suggestion
// remove .skip to run the test, be aware it does a real API call so it will update a contact in the active campaign account
```

2024-11-26 14:41 UTC, marcobottaro commented on packages/active-campaign-client/src/__tests__/helpers/listUsersCommandOutputToUser.test.ts
> +  it('should proper convert ListUsersCommandOutput to User', async () => {
```suggestion
  it('should properly convert ListUsersCommandOutput to User', async () => {
```

2024-11-26 14:56 UTC, marcobottaro requested changes
You should add a changeset file

2024-11-27 14:03 UTC, marcobottaro approved these changes

2024-11-27 14:06 UTC, marcobottaro approved these changes

2024-11-27 14:07 UTC, merged