[DEV-1279][DEV-1996] Generate sitemap xml of the site
pagopa/developer-portal pull request #1277
Opened 2024-12-17 10:52 UTC by tommaso1

#### List of Changes

Add sitemap.xml to website

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):
<img width="644" alt="Screenshot 2024-12-17 at 11 49 00" src="https://github.com/user-attachments/assets/82e3f615-4767-47d5-a0d0-da0bb99b82c6" />

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-12-18 16:05 UTC, tommaso1 commented
Add NEXT_PUBLIC_BASE_URL to .env for referncing sitemap on robots

2024-12-19 14:34 UTC, marcobottaro requested changes

2024-12-19 14:34 UTC, marcobottaro commented on apps/nextjs-website/src/app/sitemap.ts
> +  return [
Many pages are missing from the sitemap:
- solution list page
- the solution preview pages
- the solution details pages
- the webinar list page
- the webinars pages
- the guide pages
- the tutorial pages (`tutorials/come-utilizzare-correttamente-servizi-e-messaggi-in-app-io`)
- the guide and tutorial subpages
- etc.

2025-01-09 10:00 UTC, MarcoPonchia requested changes

2025-01-09 10:00 UTC, MarcoPonchia commented on apps/nextjs-website/.env.default
> +NEXT_PUBLIC_ORGANIZATION_SOCIAL_LINKS='https://x.com/PagoPA,https://www.instagram.com/pagopaspa/,https://www.linkedin.com/company/pagopa/,https://medium.com/pagopa-spa'
```suggestion
NEXT_PUBLIC_ORGANIZATION_SOCIAL_LINKS='https://x.com/PagoPA,https://www.instagram.com/pagopaspa/,https://www.linkedin.com/company/pagopa/,https://medium.com/pagopa-spa'

```

2025-01-09 10:46 UTC, marcobottaro commented on apps/nextjs-website/src/app/sitemap.ts
> +  return [
![image](https://github.com/user-attachments/assets/f168c424-b7d4-4915-bf51-e63aa3751298)

There is something wrong with:
- links to tutorial pages `<loc>https://dev.developer.pagopa.it/app-io/tutorials/[object Object]</loc>`
- links to guide pages, which link to the main page of each guide several times
- links to guide pages, where the link is malformed (the prefix is ​​repeated twice) as you can see in this example `/app-io/guides//app-io/guides`

2025-01-09 10:47 UTC, marcobottaro requested changes
You should resolve [this comment](https://github.com/pagopa/developer-portal/pull/1277#discussion_r1908536318)

2025-01-09 10:49 UTC, marcobottaro commented on apps/nextjs-website/src/app/sitemap.ts
> +    ...sectionRoutes,
`terms-of-service` is missing and i'm not sure about publishing auth and profile routes

2025-01-13 15:44 UTC, MarcoPonchia requested changes

2025-01-13 15:44 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/sitemap.ts
> +    ...profileRoutes,
```suggestion
```

2025-01-13 15:45 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/sitemap.ts
> +
```suggestion
  ];

```

2025-01-14 14:00 UTC, MarcoPonchia approved these changes

2025-01-15 11:44 UTC, marcobottaro requested changes
add tos

2025-01-16 14:03 UTC, marcobottaro commented on apps/nextjs-website/src/app/sitemap.ts
> +    },
```suggestion
    {
      url: `${baseUrl}/privacy-policy`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.3,
    },
    {
      url: `${baseUrl}/terms-of-service,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.3,
    },
```

2025-01-16 15:32 UTC, marcobottaro approved these changes

2025-01-17 16:48 UTC, merged