[DEV-2023] fix empty area on top of  solutions
pagopa/developer-portal pull request #1281
Opened 2024-12-17 13:52 UTC by MarBert

#### List of Changes

Remove empty area when browsing a solutiuon documentation

#### Motivation and Context

Fixes in the project documentation, broke the solution page 

#### How Has This Been Tested?

Localhost
#### Screenshots (if appropriate):
<img width="959" alt="image" src="https://github.com/user-attachments/assets/1b5e6d37-d878-4318-a049-89e37da69423" />

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-12-18 11:52 UTC, marcobottaro requested changes

2024-12-18 11:52 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/GitBookTemplate/GitBookTemplate.tsx
> +  const headerPadding = hasHeader ? '60px' : '-80px';
```suggestion
  const paddingTop = hasHeader ? '60px' : '-80px';
```
or `headerPaddingTop` or an object containing paddingTop and paddingX

2024-12-18 11:52 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/GitBookTemplate/GitBookTemplate.tsx
> +          <Box sx={{ paddingTop: headerPadding, paddingX: '40px' }}>
```suggestion
          <Box sx={{ paddingTop: paddingTop, paddingX: '40px' }}>
```

2024-12-20 10:00 UTC, marcobottaro approved these changes

2025-01-07 16:08 UTC, MarcoPonchia approved these changes

2025-01-08 08:59 UTC, merged