[DEV-2003] add missing title metadata
pagopa/developer-portal pull request #1283
Opened 2024-12-18 08:55 UTC by MarBert

#### List of Changes

Add title metadata to Solutions, Privacy Policy and TOS

#### Motivation and Context

The title was missing

#### How Has This Been Tested?

On localhost

#### Screenshots (if appropriate):
<img width="260" alt="image" src="https://github.com/user-attachments/assets/9affb844-c50b-4080-8d95-d0b4dde317bf" />
<img width="254" alt="image" src="https://github.com/user-attachments/assets/e13aa460-d694-49ba-b19a-a829dd73a848" />
<img width="258" alt="image" src="https://github.com/user-attachments/assets/8dfd82b1-eda4-418c-a4bc-af5e1220e1df" />

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-12-18 14:05 UTC, marcobottaro requested changes

2024-12-18 14:05 UTC, marcobottaro commented on .changeset/sharp-terms-walk.md
> +Add title metadata to Solutions, Privacy Policy and TOS
```suggestion
Add title metadata to Solutions, Privacy Policy and TOS pages
```

2024-12-18 14:05 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/PrivacyPolicyTemplate/PrivacyPolicyAtom.tsx
You should rename this file as `PrivacyPolicyTemplate.tsx`

2024-12-20 10:01 UTC, marcobottaro approved these changes

2025-01-07 17:49 UTC, MarcoPonchia approved these changes

2025-01-09 08:48 UTC, merged