[DEV-422] - Add tutorial list page layout
pagopa/developer-portal pull request #146
Opened 2023-07-06 16:33 UTC by marcobottaro

#### List of Changes
- Rename constants and file containing acronyms using camelCase
- Add layout to Tutorial list page
- Add content structure to handle Tutorial list for each product
- Change product type

#### Motivation and Context
The page was empty

#### How Has This Been Tested?
Manually

#### Screenshots (if appropriate):
![image](https://github.com/pagopa/developer-portal/assets/39835990/d5a2d2d9-dc59-4ded-a07a-5761ef581f20)

#### Types of changes
- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/appIo/tutorialLists.ts
> +    path: '/app-io/tutorials/quale-accordo-di-adesione-scegliere',
```suggestion
    path: `${appIoTutorialListsPath.path}/quale-accordo-di-adesione-scegliere',
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/appIo/tutorialLists.ts
> +    path: '/app-io/tutorials/come-allegare-documenti-a-un-messaggio',
```suggestion
    path: `${appIoTutorialListsPath.path}/come-allegare-documenti-a-un-messaggio',
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
> +    path: '/io-sign/tutorials/1',
```suggestion
    path: `${ioSignTutorialListsPath.path}/1`,
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
> +    path: '/io-sign/tutorials/2',
```suggestion
    path: `${ioSignTutorialListsPath.path}/2`,
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
> +    path: '/io-sign/tutorials/3',
```suggestion
    path: `${ioSignTutorialListsPath.path}/3`,
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/pagoPa/tutorialLists.ts
> +    path: '/pago-pa/tutorials/come-richiedere-pagamenti-che-contengono-marca-da-bollo-digitale',
```suggestion
    path: `${pagoPaTutorialListsPath.path}/come-richiedere-pagamenti-che-contengono-marca-da-bollo-digitale`,
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/pagoPa/tutorialLists.ts
> +    path: '/pago-pa/tutorials/come-avviare-un-esercizio-come-ente-creditore-su-pagopa',
```suggestion
    path: `${pagoPaTutorialListsPath.path}/come-avviare-un-esercizio-come-ente-creditore-su-pagopa`,
```

2023-07-06 16:46 UTC, datalek commented on apps/nextjs-website/src/_contents/pagoPa/tutorialLists.ts
> +    path: '/pago-pa/tutorials/come-stampare-un-avviso-di-pagamento-in-formato-pdf',
```suggestion
    path: `${pagoPaTutorialListsPath.path}/come-stampare-un-avviso-di-pagamento-in-formato-pdf`,
```

2023-07-07 07:35 UTC, datalek requested changes

2023-07-07 07:35 UTC, datalek commented on apps/nextjs-website/src/pages/[productSlug]/tutorials.tsx
> +                date: new Date(),
```suggestion
                date: new Date(tutorial.dateString),
```

2023-07-07 08:42 UTC, datalek commented on apps/nextjs-website/src/pages/[productSlug]/tutorials.tsx
> +import { Newsroom } from '@pagopa/pagopa-editorial-components';
```suggestion
import Newsroom from '@/editorialComponents/Newsroom/Newsroom';
```

2023-07-07 09:07 UTC, marcobottaro commented on apps/nextjs-website/src/pages/[productSlug]/tutorials.tsx
> +import { Newsroom } from '@pagopa/pagopa-editorial-components';
Direi proprio di sì!!!

2023-07-07 09:15 UTC, datalek approved these changes

2023-07-07 09:15 UTC, merged