Fix breadcrumbs
pagopa/developer-portal pull request #169
Opened 2023-07-12 09:09 UTC by MarcoPonchia

#### List of Changes

- align Site Header margin to product header
- fix breadcrumb

#### Motivation and Context

fix breadcrumbs

#### How Has This Been Tested?

User can see breadcrumbs for tutorials and guides pages http://localhost:3000/app-io/guides http://localhost:3000/app-io/tutorials

#### Screenshots (if appropriate):
![screenshot-localhost_3000-2023 07 12-10_12_41](https://github.com/pagopa/developer-portal/assets/24475319/4567d55e-9558-4a1a-a632-e5e3d97d3a52)
![screenshot-localhost_3000-2023 07 12-10_12_18](https://github.com/pagopa/developer-portal/assets/24475319/b78d69e4-01eb-4aac-be06-886b3817139d)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-13 07:50 UTC, datalek commented
The screenshot shows that the breadcrumb and page title are not aligned

2023-07-13 10:06 UTC, MarcoPonchia commented
> The screenshot shows that the breadcrumb and page title are not aligned

For guides pages retrivered from gitbook i had check with design team this feature and this should be the definitive version mockup will be updated.
For other pages breadcrumbs are now align to container below. Current mismatch of align is due to Abastract  component that is already fixed in other PR.

2023-07-14 09:57 UTC, datalek requested changes

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/fixtures/mockProduct.ts
> +export const mockProduct: Product = {
```suggestion
export const aProduct: Product = {
```

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/fixtures/mockProduct.ts
Usually we put this kind of information into a `data.ts` file

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/helpers/breadcrumbs.helpers.test.ts
Usually we put tests into the folder of  the file to test. What do you think to move this file under `src/helpers/__tests__/*`?

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/helpers/breadcrumbs.helpers.test.ts
> +  expect(breadcrumbsPaths[2].name).toEqual(product.subpaths.tutorials?.name);
```suggestion
  const actual = productPageToBreadcrumbs({
    homepageTitle,
    product,
    path,
  });
  const expected = [
    { path: '/', name: homepageTitle },
    { path: product.subpaths.overview.path, name: product.name },
    { path, name: product.subpaths.tutorials?.name },
  ];
  expect(actual).toStrictEqual(expected);
```

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/helpers/breadcrumbs.helpers.test.ts
> +it('should create breadcrumbs successfully', () => {
Usually we write test in the following form:

```ts
describe('methodName', () => {
  it('should produce a breadcrumb given a product', () => {
      // test here
  });
});
```

2023-07-14 09:57 UTC, datalek commented on apps/nextjs-website/src/__tests__/helpers/breadcrumbs.helpers.test.ts
> +  const paths: readonly Path[] = [
What do you think to move this test on a different `it`?

2023-08-03 14:48 UTC, datalek commented
The activity is tracked by the issue [DEV-859](https://pagopa.atlassian.net/browse/DEV-859) and not yet ready do be developed.

2023-08-03 14:48 UTC, closed without merging