Features/parse embed
pagopa/developer-portal pull request #196
Opened 2023-07-21 09:20 UTC by kin0992

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-21 09:23 UTC, kin0992 commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +  it.only('should parse embed', () => {
```suggestion
  it('should parse embed', () => {
```

2023-07-21 12:34 UTC, datalek requested changes

2023-07-21 12:34 UTC, datalek commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +    ]);
Can you add a test that covers the [self-closed tag scenario](https://github.com/pagopa/devportal-docs/blob/docs/from-gitbook/docs/v7eFccIIRcGfOIG6IHkT/esperienza-per-il-cittadino/app-io/README.md?plain=1#L22)?

2023-07-24 09:07 UTC, datalek approved these changes
👓

2023-07-24 09:07 UTC, datalek commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +        []
You can omit the `[]` from constructor.

2023-07-24 09:23 UTC, merged