Dev 622 remove crawler block
pagopa/developer-portal pull request #301
Opened 2023-10-03 08:56 UTC by tommaso1

#### List of Changes

Removed robots.txt file

#### Motivation and Context
Now web robots (typically search engine robots) can crawl pages on this website. 
Deleting the file will make the site crawable on all environments. 
To restrict this to only work in production we could do it dynamically creating a `robots.ts` file on the root app directory with the following content

```
import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  if (process.env.NODE_ENV !== 'production') {
    return {
      rules: {
        userAgent: '*',
        disallow: '/',
      },
    };
  } else {
    return {
      rules: {
        userAgent: '*',
        allow: '/',
      },
    };
  }
}

```
This will allow us to have a better control over the environment the crawler are blocked on, but will require next js not to be configured as export.

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-03 15:04 UTC, datalek requested changes

2023-10-03 15:04 UTC, datalek commented on apps/nextjs-website/public/robots.txt
By removing this file, both environments can be scanned, but the ticket says that only the production environment should be. As you described on PR's body we should use `robots.ts`

2023-10-10 15:20 UTC, kin0992 commented
We need to wait to merge this PR

2023-10-23 13:18 UTC, marcobottaro approved these changes

2023-11-23 10:55 UTC, kin0992 requested changes

2023-11-23 10:55 UTC, kin0992 commented on .github/workflows/code_review.yaml
> +          allow_crawler: ${{ secrets.ALLOW_CRAWLER }}
```suggestion
          allow_crawler: ${{ vars.ALLOW_CRAWLER }}
```

2023-11-23 10:55 UTC, kin0992 commented on .github/workflows/deploy_website.yaml
> +          allow_crawler: ${{ secrets.ALLOW_CRAWLER }}
```suggestion
          allow_crawler: ${{ vars.ALLOW_CRAWLER }}
```

2023-11-23 10:55 UTC, kin0992 commented on .github/workflows/deploy_website.yaml
> +          allow_crawler: ${{ secrets.ALLOW_CRAWLER }}
```suggestion
          allow_crawler: ${{ vars.ALLOW_CRAWLER }}
```

2023-11-23 15:25 UTC, kin0992 approved these changes

2023-11-24 07:53 UTC, datalek approved these changes

2023-11-24 07:53 UTC, merged