[DEV-876] Next intl setup
pagopa/developer-portal pull request #320
Opened 2023-10-16 13:37 UTC by tommaso1

#### List of Changes
Add next intl to the project, set up translation files

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-16 16:28 UTC, kin0992 requested changes

2023-10-16 16:28 UTC, kin0992 commented on package.json
> +    "next-intl": "^2.20.2"
```suggestion
  }
```
the dependency should not be installed here, but you should add it into its app `nextjs-website`

2023-10-19 12:29 UTC, marcobottaro approved these changes

2023-10-20 07:34 UTC, kin0992 requested changes

2023-10-20 07:34 UTC, kin0992 commented on apps/nextjs-website/src/messages/en.json
Is it possible to use a real (even simple) translation and show how it's going to be used in the codebase instead of the Hello World?

Even one translation is enough for me

2023-10-20 09:21 UTC, MarcoPonchia approved these changes

2023-10-31 16:23 UTC, kin0992 requested changes

2023-10-31 16:23 UTC, kin0992 commented on apps/nextjs-website/src/app/layout.tsx
> +            {environment === 'prod' && (
Let's start reducing code duplication: now you can use the `isProduction` available [here](https://github.com/pagopa/developer-portal/blob/046d4aaaa49809ffccd8b7f21f7f0ec5d4551b57/apps/nextjs-website/src/config.ts#L6)
```suggestion
            {isProduction && (
```

2023-10-31 16:23 UTC, kin0992 commented on apps/nextjs-website/src/app/layout.tsx
> +            {environment === 'prod' && (
If you accept this suggestion from here, you have to add the import manually 😄

2023-10-31 17:42 UTC, kin0992 approved these changes

2023-10-31 17:43 UTC, merged