[DEV-828] Cookies prefences footer link
pagopa/developer-portal pull request #333
Opened 2023-10-18 14:29 UTC by tommaso1

#### List of Changes

Add a link on resources section on the website footer. Clicking that link will open one trust cookie preferences.

(You have to have one trust enabled to use it -- the environment should be prod)

#### Motivation and Context

https://pagopa.atlassian.net/jira/software/projects/DEV/boards/280?selectedIssue=DEV-828

#### How Has This Been Tested?

Goinig on layout.ts, enabling cookies for every environment. Click on the link on the footer.

#### Screenshots (if appropriate):
![Screen1png](https://github.com/pagopa/developer-portal/assets/18684459/92113f71-c169-408d-9d54-18ec7ef5de5d)
![Screen2](https://github.com/pagopa/developer-portal/assets/18684459/ea9c2943-543e-404c-8e23-d0b062a90775)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-19 12:28 UTC, marcobottaro approved these changes

2023-10-20 09:57 UTC, MarcoPonchia approved these changes

2023-10-24 09:45 UTC, datalek requested changes

2023-10-24 09:45 UTC, datalek commented on apps/nextjs-website/src/components/atoms/SiteFooter/SiteFooter.tsx
> +      // @ts-ignore, OneTrust is a global variable
```suggestion
      // @ts-expect-error: The system assumes OneTrust is loaded
```

2023-10-31 15:17 UTC, datalek approved these changes

2023-10-31 15:18 UTC, merged