Dev 1067 webinar detail page
pagopa/developer-portal pull request #363
Opened 2023-11-02 18:16 UTC by MarcoPonchia

#### List of Changes

depends on: https://github.com/pagopa/developer-portal/pull/359
Add webinar detail page and existing component

#### Motivation and Context

Add webinar detail page routing

#### How Has This Been Tested?

User can see webinar detail page on: http://localhost:3000/webinars/comunicazioni-a-valore-legale

#### Screenshots (if appropriate):
![Screenshot from 2023-11-02 19-13-07](https://github.com/pagopa/developer-portal/assets/24475319/d3beedd4-266d-448d-9dc8-50ab3709d0e4)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-09 15:41 UTC, marcobottaro commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +        <StartInfo
The background color of this section is not #FAFAFA, but #F2F2F2 and the title is too close to the cards.
![image](https://github.com/pagopa/developer-portal/assets/39835990/c38e5d06-eb2f-444d-8170-c0050d203bb5)

2023-11-14 11:27 UTC, marcobottaro approved these changes

2023-11-14 11:45 UTC, marcobottaro commented
![image](https://github.com/pagopa/developer-portal/assets/39835990/18d20a39-920a-4856-901e-c1a99dce3d87)

vertical padding should be 64px

2023-11-14 11:57 UTC, marcobottaro commented
![image](https://github.com/pagopa/developer-portal/assets/39835990/b5dfb8ce-e51b-49f8-b040-709b0e457198)
`font-weight: 600; font-size: 24px;`

2023-11-14 12:00 UTC, marcobottaro requested changes
Fix these little differences with Figma:
- https://github.com/pagopa/developer-portal/pull/363#issuecomment-1810050595
- https://github.com/pagopa/developer-portal/pull/363#issuecomment-1810053344
- https://github.com/pagopa/developer-portal/pull/363#issuecomment-1810068129

2023-11-14 13:43 UTC, marcobottaro approved these changes

2023-11-15 12:03 UTC, kin0992 approved these changes

2023-11-15 12:32 UTC, merged