[DEV-1120] Add agreements page
pagopa/developer-portal pull request #406
Opened 2023-11-16 15:25 UTC by marcobottaro

#### List of Changes

Add agreements page

#### Motivation and Context

This is a page in the profile section. The menu will come in a separate PR

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):
![image](https://github.com/pagopa/developer-portal/assets/39835990/d02d4f10-d041-4bda-b5a5-e237d6705c3f)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-17 13:40 UTC, MarcoPonchia requested changes

2023-11-17 13:40 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/profile/agreements/page.tsx
> +    <Stack sx={{ margin: '30px', width: '100%', maxWidth: '694px' }}>
```suggestion
    <Stack sx={{ padding: '30px', width: '100%', maxWidth: '694px' }}>
```

2023-11-17 15:59 UTC, MarcoPonchia approved these changes

2023-11-20 09:46 UTC, kin0992 approved these changes

2023-11-20 09:46 UTC, merged