Dev 1168 manage webinars subscription withuser preferences
pagopa/developer-portal pull request #443
Opened 2023-11-23 10:41 UTC by MarcoPonchia

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-23 17:55 UTC, marcobottaro requested changes

2023-11-23 17:55 UTC, marcobottaro commented on apps/nextjs-website/src/__tests__/helpers/userPreferences.helpers.test.ts
> +it('should return false if webinar subscription not exists', () => {
```suggestion
it('should return false if webinar subscription does not exist', () => {
```

2023-11-23 17:55 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/userPreferences.helpers.ts
> +}
:+1:

2023-11-23 17:55 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/userPreferences.helpers.ts
> +  }
```suggestion
  if (currentUserPreferences.subscribedWebinarSlugs.includes(slug)) {
    return attributes;
  }
  
  return mergeUserPreferencesToAttributes(
    {
      subscribedWebinarSlugs: [
        ...currentUserPreferences.subscribedWebinarSlugs,
        slug,
      ],
    },
    attributes
  );
```

2023-11-23 17:55 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/userPreferences.helpers.ts
> +  }
```suggestion
  if (!currentUserPreferences.subscribedWebinarSlugs.includes(slug)) {
    return attributes;
  }
  
return mergeUserPreferencesToAttributes(
  {
    subscribedWebinarSlugs:
      currentUserPreferences.subscribedWebinarSlugs.filter(
        (subscriptionSlug) => subscriptionSlug !== slug
      ),
  },
  attributes
);
```

2023-11-23 17:55 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/userPreferences.helpers.ts
> +export function webinarSubscriptionPresent(
```suggestion
export function webinarSubscriptionExists(
```

2023-11-24 07:23 UTC, datalek requested changes
Once subscribed to the webinar, the button in the homepage is not updated once the page is refreshed

2023-11-24 09:39 UTC, MarcoPonchia commented
> Once subscribed to the webinar, the button in the homepage is not updated once the page is refreshed

Fixed 
[Screencast from 24-11-2023 10:38:46.webm](https://github.com/pagopa/developer-portal/assets/24475319/f6ed8772-8acb-49d1-9d43-903c77034259)

2023-11-24 15:13 UTC, kin0992 approved these changes

2023-11-24 15:13 UTC, merged