[DEV-1148]: resend mfa code
pagopa/developer-portal pull request #484
Opened 2023-11-30 14:12 UTC by MikeAtUqido

#### List of Changes

* Add the possibility to resend the MFA code
* Disable the MFA code after the first try

#### Motivation and Context

The user needs to be able to resend the MFA code and the code should be valid only once

#### How Has This Been Tested?

 - [x] Manually
 - [ ] 
#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-01 09:56 UTC, marcobottaro requested changes
Maybe the "Continue" button should be active again after clicking "Submit a new code" (the copy is wrong). There is also an inconsistency issue with the "Resend email" button in the footer (after the phrase "Check junk mail or"). I think we should take a look at the whole flow with the design team!

[screencast-localhost_3000-2023.12.01-10_47_54.webm](https://github.com/pagopa/developer-portal/assets/39835990/010976c7-d838-46ab-ba26-19a2f5999ea9)

2023-12-13 14:05 UTC, MarcoPonchia approved these changes

2023-12-13 15:43 UTC, tommaso1 approved these changes

2024-01-02 11:24 UTC, datalek requested changes
I agree with @marcobottaro, the flow should be reviewed with the team.There are two link that do the same thing (`Reinvia e-mail` and `Invia nuovo codice`). The `Invia nuovo codice` doesn't provide any feedback once pressed.

![Screenshot 2024-01-02 at 12 14 11](https://github.com/pagopa/developer-portal/assets/4775679/34712758-699a-4367-a678-93508eace607)

2024-01-11 10:31 UTC, marcobottaro commented
> I agree with @marcobottaro, the flow should be reviewed with the team. There are two link that do the same thing (`Reinvia e-mail` and `Invia nuovo codice`). The `Invia nuovo codice` doesn't provide any feedback once pressed.
> 
> ![Screenshot 2024-01-02 at 12 14 11](https://private-user-images.githubusercontent.com/4775679/293681627-34712758-699a-4367-a678-93508eace607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjkzNTksIm5iZiI6MTcwNDk2OTA1OSwicGF0aCI6Ii80Nzc1Njc5LzI5MzY4MTYyNy0zNDcxMjc1OC02OTlhLTQzNjctYTY3OC05MzUwOGVhY2U2MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTAzMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmExNDU4MzI3NzUzYzg4YzkwNDM5OWYyMTcyZjg4MmMzYzQ3YzM5NzA5NTQzZjMxZmE2NGQ2YTRjM2RhYmI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l_51vUn9f9T8zsf80JD-8zWuEJOoNJraEhR8C3FBuxo)
> 
> UPDATE: Checkout the comment on [Jira](https://pagopa.atlassian.net/browse/DEV-1148?focusedCommentId=112897)

So let's remove "invia nuovo codice"

2024-01-11 10:37 UTC, closed without merging