[DEV-1213] Replace SiteHeader's mobile layout
pagopa/developer-portal pull request #491
Opened 2023-12-04 16:18 UTC by marcobottaro

#### List of Changes

Replace SiteHeader's mobile layout

#### Motivation and Context

This PR changes header layout to correspond to Figma's

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):
![image](https://github.com/pagopa/developer-portal/assets/39835990/b07f9954-4442-44f9-b571-dafcba584c13)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-08 14:26 UTC, kin0992 commented
@marcobottaro please resolve the conflicts

2024-01-11 17:31 UTC, MarcoPonchia requested changes
i notice some difference to figma in both menu and product header from mobile view
mock:
![Screenshot from 2024-01-11 18-23-08](https://github.com/pagopa/developer-portal/assets/24475319/42e7b105-8102-4de9-9fad-65f49a3355b2)
site:
![Screenshot from 2024-01-11 18-23-26](https://github.com/pagopa/developer-portal/assets/24475319/c269982b-d787-488c-9b1e-d5b1337624fc)

2024-01-16 16:00 UTC, MarcoPonchia requested changes

2024-01-16 16:00 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/ProductHeader/ProductHeader.tsx
>          transition: 'all 0.5s linear',
I think `transition: all` cause width resizing problem:
[Screencast from 16-01-2024 16:56:55.webm](https://github.com/pagopa/developer-portal/assets/24475319/7deff611-c30d-4b17-86bf-092e0ea4a48f)
```suggestion
        transition: 'top 0.5s linear',
```

2024-01-17 16:41 UTC, MarcoPonchia approved these changes

2024-01-18 09:56 UTC, merged