[DEV-1080] Webinar questions form
pagopa/developer-portal pull request #492
Opened 2023-12-05 09:43 UTC by jeremygordillo

#### List of Changes

#### Motivation and Context

We need a form where webinar registrants can submit questions

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-06 10:00 UTC, marcobottaro requested changes

2023-12-06 10:00 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/WebinarQuestionsForm/WebinarQuestionsForm.tsx
> +        onChange={handleChange}
```suggestion
        onChange={handleChange}
        sx={{ flexGrow: 1 }}
```

2023-12-06 10:00 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/WebinarQuestionsForm/WebinarQuestionsForm.tsx
> +        onChange={handleChange}
The result will be like this:
![image](https://github.com/pagopa/developer-portal/assets/39835990/93a83d0f-b3c1-442a-a43d-81ee6ebaa777)

mobile:
![image](https://github.com/pagopa/developer-portal/assets/39835990/98c1ad15-5cf2-44b4-95db-023719b04eb8)

2023-12-06 10:00 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/WebinarDetailTemplate/WebinarDetailTemplate.tsx
> +        <WebinarQuestionsForm />
You can remove this temporary line (and the import at line 16)

2023-12-07 15:33 UTC, MarcoPonchia approved these changes

2023-12-11 14:23 UTC, datalek requested changes

2023-12-11 14:23 UTC, datalek commented on apps/nextjs-website/src/components/organisms/WebinarQuestionsForm/WebinarQuestionsForm.tsx
> +    console.log(question);
```suggestion
```

2023-12-11 14:41 UTC, kin0992 approved these changes

2023-12-11 14:42 UTC, datalek approved these changes

2023-12-11 14:43 UTC, merged