[DEV-1022] Editable profile
pagopa/developer-portal pull request #499
Opened 2023-12-07 10:54 UTC by tommaso1

#### List of Changes

Editable profile page

#### Motivation and Context

DEV-1022

#### How Has This Been Tested?

go to `/profile/personal-data`, then click "edit"

#### Screenshots (if appropriate):
![proof](https://github.com/pagopa/developer-portal/assets/18684459/090965d9-c3bd-4808-9c99-7be35c9d0c37)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-11 12:07 UTC, marcobottaro requested changes

2023-12-11 12:07 UTC, marcobottaro commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
> +  }, [user?.attributes])
This file has linting issues

2023-12-11 12:07 UTC, marcobottaro commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
> +          title: t('personalData.fields.sector'),
This field should be e Select like in the signu up form
![image](https://github.com/pagopa/developer-portal/assets/39835990/182d6e77-47b2-40b2-9cf0-79a5735ccdb7)
Figma:
![image](https://github.com/pagopa/developer-portal/assets/39835990/89b0c2e3-3c26-457a-a75b-e6ee5c23db99)

2023-12-11 15:51 UTC, marcobottaro approved these changes

2023-12-13 16:32 UTC, marcobottaro commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
> +              given_name: items[0].value || '',
Maybe you could replace this and the following `|| ''` with something like this:
```suggestion
              ...(items[0].value && { given_name: items[0].value }),
```

2023-12-14 10:08 UTC, MarcoPonchia requested changes
User should access to edit form also from button "Inserisci" visible on [personal-data](http://localhost:3000/profile/personal-data) when there isn't any information relative to some field.
[Screencast from 14-12-2023 10:50:24.webm](https://github.com/pagopa/developer-portal/assets/24475319/d265121a-5f07-4fa8-8ccf-84d361475c40)

2024-01-02 09:51 UTC, datalek requested changes
There are some conflicts to resolve :/

2024-01-17 12:04 UTC, MarcoPonchia requested changes
I cannot save an empty field, as you can see in this clip when i save an empty field the previus value show up after save. I also think is bettere to align "name" and "surname" fields to signup form and make  theme required, if their empty form should show an error on relative input and save should be disabled
[Screencast from 17-01-2024 12:56:23.webm](https://github.com/pagopa/developer-portal/assets/24475319/4b7c7117-9224-4919-a14a-f06fcdba1470)

2024-01-18 11:04 UTC, MarcoPonchia requested changes

2024-01-18 11:04 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
>      setShowModal(true);
```suggestion
```

2024-01-18 11:04 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
>    const [showModal, setShowModal] = useState(false);
```suggestion
```

2024-01-18 11:04 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
>    const router = useRouter();
```suggestion
```

2024-01-18 11:04 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/profile/personal-data/page.tsx
> +                }),
```suggestion
                ...{
                  given_name: items[0].value || user.attributes.given_name,
                  family_name: items[1].value || user.attributes.family_name,
                  'custom:job_role': items[2].value || '',
                  'custom:company_type':
                    items[3].value || user.attributes['custom:company_type'],
                },
```

2024-01-18 11:04 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/molecules/InfoCard/InfoCardProfile.tsx
> +                value: value == '' ? ' ' : value,
```suggestion
                value,
```

2024-01-18 13:14 UTC, MarcoPonchia approved these changes

2024-01-18 15:14 UTC, kin0992 commented
@tommaso1 please add the changeset in this PR

2024-01-18 17:28 UTC, MarcoPonchia requested changes

2024-01-18 17:28 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/InfoCardItem/InfoCardItemProfile.tsx
> +  );
```suggestion
  if (!infoCardItem.editing) {
    return (
      <Stack
        my={{ xs: 1, md: 3 }}
        flexDirection={{ xs: 'column', md: 'row' }}
        alignItems={{ xs: 'flex-start', md: 'center' }}
        gap={2}
      >
        <Typography
          variant='body2'
          fontSize={16}
          minWidth={{ xs: 'auto', md: '170px' }}
        >
          {infoCardItem.title}
        </Typography>
        {infoCardItem.value && infoCardItem.value != '' ? (
          <Typography
            minHeight={'24px'}
            fontSize={16}
            flexGrow={1}
            fontWeight={700}
          >
            {infoCardItem.type === 'select'
              ? infoCardItem.values.find(
                  ({ value }) => value === infoCardItem.value
                )?.title
              : infoCardItem.value}
          </Typography>
        ) : (
          <ButtonNaked
            onClick={infoCardItem.onInsertPressed}
            color='primary'
            sx={{ paddingLeft: 0, paddingRight: 0 }}
          >
            {t('insert')}
          </ButtonNaked>
        )}
      </Stack>
    );
  }

  return (
    <Stack spacing={2} mb={2} sx={{ marginTop: '2rem' }}>
      <FormControl variant='outlined'>
        {infoCardItem.type === 'text' ? (
          infoCardItem.required ? (
            <RequiredTextField
              label={infoCardItem.title}
              value={infoCardItem.value ?? ''}
              onChange={({ target: { value } }) => {
                infoCardItem.onValue && infoCardItem.onValue(value);
              }}
              helperText={translations.shared.requiredFieldError}
            />
          ) : (
            <TextField
              variant='outlined'
              id={infoCardItem.title}
              type={'text'}
              onChange={({ target: { value } }) => {
                infoCardItem.onValue && infoCardItem.onValue(value);
              }}
              value={infoCardItem.value}
              label={infoCardItem.title}
              size='small'
            />
          )
        ) : (
          <>
            <InputLabel
              id={'company-field'}
              sx={{ backgroundColor: 'white', paddingX: '8px' }}
            >
              {infoCardItem.title}
              {infoCardItem.required ? '*' : ''}
            </InputLabel>
            <Select
              labelId='company-field'
              id='company-field-select'
              value={
                infoCardItem.values.find(
                  ({ value }) => value === infoCardItem.value
                )?.value || ''
              }
              onChange={({ target: { value } }) =>
                infoCardItem.onValue &&
                infoCardItem.onValue(
                  infoCardItem.values.find(({ value: v }) => v === value)
                    ?.value || ''
                )
              }
              sx={{ padding: '8.5px 14px' }}
              inputProps={{
                sx: {
                  padding: 0,
                },
              }}
            >
              {infoCardItem.values.map(({ title, value }) => (
                <MenuItem key={value} value={value}>
                  {title}
                </MenuItem>
              ))}
            </Select>
          </>
        )}
      </FormControl>
    </Stack>
  );
```

2024-01-18 17:28 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/InfoCardItem/InfoCardItemProfile.tsx
> +  Typography,
```suggestion
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  TextField,
  Typography,
```

2024-01-18 17:35 UTC, MarcoPonchia requested changes

2024-01-18 17:35 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/atoms/InfoCardItem/InfoCardItemProfile.tsx
> +    );
```suggestion
  if (infoCardItem.editing) {
    return (
      <Stack spacing={2} mb={2} sx={{ marginTop: '2rem' }}>
        <FormControl variant='outlined'>
          {infoCardItem.type === 'text' ? (
            infoCardItem.required ? (
              <RequiredTextField
                label={infoCardItem.title}
                value={infoCardItem.value ?? ''}
                onChange={({ target: { value } }) => {
                  infoCardItem.onValue && infoCardItem.onValue(value);
                }}
                helperText={translations.shared.requiredFieldError}
              />
            ) : (
              <TextField
                variant='outlined'
                id={infoCardItem.title}
                type={'text'}
                onChange={({ target: { value } }) => {
                  infoCardItem.onValue && infoCardItem.onValue(value);
                }}
                value={infoCardItem.value}
                label={infoCardItem.title}
                size='small'
              />
            )
          ) : (
            <>
              <InputLabel
                id={'company-field'}
                sx={{
                  backgroundColor: 'white',
                  paddingX: '8px',
                  marginLeft: '-6px',
                }}
              >
                {infoCardItem.title}
                {infoCardItem.required ? '*' : ''}
              </InputLabel>
              <Select
                labelId='company-field'
                id='company-field-select'
                value={
                  infoCardItem.values.find(
                    ({ value }) => value === infoCardItem.value
                  )?.value || ''
                }
                onChange={({ target: { value } }) =>
                  infoCardItem.onValue &&
                  infoCardItem.onValue(
                    infoCardItem.values.find(({ value: v }) => v === value)
                      ?.value || ''
                  )
                }
                sx={{ padding: '8.5px 14px' }}
                inputProps={{
                  sx: {
                    padding: 0,
                  },
                }}
              >
                {infoCardItem.values.map(({ title, value }) => (
                  <MenuItem key={value} value={value}>
                    {title}
                  </MenuItem>
                ))}
              </Select>
            </>
          )}
        </FormControl>
      </Stack>
    );
  }
```

2024-01-19 08:26 UTC, marcobottaro commented
When the sector value is missing the user doesn't see the "Insert" button:
![image](https://github.com/pagopa/developer-portal/assets/39835990/d45d8a04-0d52-402d-ad5d-a6e79e506db5)

2024-01-19 08:28 UTC, marcobottaro commented
When the user edits the profile settings and the sector is empty, the placeholder is not aligned:
![image](https://github.com/pagopa/developer-portal/assets/39835990/bae35ff0-fa7e-43b7-97c2-1c6321bc14ba)

2024-01-19 08:29 UTC, marcobottaro requested changes
Look at the comments

2024-01-19 10:14 UTC, MarcoPonchia commented
> When the sector value is missing the user doesn't see the "Insert" button: ![image](https://private-user-images.githubusercontent.com/39835990/298000453-d45d8a04-0d52-402d-ad5d-a6e79e506db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTc1MzQsIm5iZiI6MTcwNTY1NzIzNCwicGF0aCI6Ii8zOTgzNTk5MC8yOTgwMDA0NTMtZDQ1ZDhhMDQtMGQ1Mi00MDJkLWFkNWQtYTZlNzllNTA2ZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5NDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZjY5NTFhZjczZjNhNjdiMTA3ZjlmOGFiN2I3NDQ3YWJlZTNjZGExZjk0MDdmODA3Nzg5OGFiNjY5Y2ViNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1KoP2QaBxIu4nCTwDtbh-2GbiKA4PZdIMePV3B-MeQ)

This case is not repeatable. I think is due to some old dirty data in your account not related to enum.

2024-01-19 10:15 UTC, MarcoPonchia approved these changes

2024-01-19 10:16 UTC, marcobottaro approved these changes

2024-01-19 10:26 UTC, merged

2024-01-19 10:54 UTC, kin0992 commented
in this PR a changeset would have been useful @MarcoPonchia @marcobottaro @tommaso1