[DEV-1229] Manage missing file end tag in markdown files
pagopa/developer-portal pull request #514
Opened 2023-12-13 09:30 UTC by jeremygordillo

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

[Caricamento massivo iban](http://localhost:3000/pago-pa/guides/manuale-bo-ec/v1.0/manuale-operativo-back-office-pagopa-ente-creditore/funzionalita/gestione-iban/caricamento-massivo-iban)

[Modelli base]([/pago-pa/guides/avviso-pagamento/3.2.0/allegato-1/modelli-base](http://localhost:3000/pago-pa/guides/avviso-pagamento/3.2.0/allegato-1/modelli-base))

<img width="993" alt="image" src="https://github.com/pagopa/developer-portal/assets/16854782/29d79693-2cad-4447-b711-a377cab3f07d">

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-13 10:23 UTC, marcobottaro commented
[/pago-pa/guides/manuale-bo-ec/v1.0/manuale-operativo-back-office-pagopa-ente-creditore/funzionalita/gestione-iban/caricamento-massivo-iban](https://github.com/pagopa/developer-portal/pull/498#issuecomment-1849702173)

2023-12-13 11:02 UTC, marcobottaro approved these changes

2024-01-02 14:58 UTC, datalek requested changes
It's not clear when the old implementation fails. I would suggest adding a test case that fails with the old implementation but doesn't with the new one

2024-01-08 10:33 UTC, jeremygordillo commented
> It's not clear when the old implementation fails. I would suggest adding a test case that fails with the old implementation but doesn't with the new one

@datalek The error was generated by this specific case:

```md
{% tabs %}
{% tab title="Tab 1" %}
Tab 1 Content

{% file src="path/to/file" %}
{% endtab %}

{% tab title="Tab 2" %}
Tab 2 Content

{% file src="path/to/file" %}
{% endtab %}
{% endtabs %}
```

When we have a file without closing tag inside a tab, the parser performs incorrect parsing. So, to avoid problems with this case, I created a regex to add the closing tag when it is missing.

2024-01-08 14:15 UTC, datalek commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +    ]);
It seems that the test does not break with the old implementation; I would expect it to break with the old implementation

2024-01-09 09:20 UTC, datalek approved these changes
LGTM

2024-01-09 09:20 UTC, datalek commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +    ]);
My mistake, I didn't take the regex into account.

2024-01-09 09:32 UTC, merged