[DEV-1253] Translations refactor
pagopa/developer-portal pull request #539
Opened 2023-12-29 16:12 UTC by jeremygordillo

#### List of Changes

Moved some translations from `apps/nextjs-website/src/_contents/translations.ts` to `apps/nextjs-website/src/messages/it.json`

#### Motivation and Context

We moved translations to be able to use `next-intl` lib

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-08 14:24 UTC, marcobottaro requested changes

2024-01-08 14:24 UTC, marcobottaro commented on apps/nextjs-website/src/config.ts
> +export const languages = [{ id: 'it', value: 'Italiano' }];
You could use `defaultLanguage`

2024-01-08 14:56 UTC, datalek approved these changes
LGTM

2024-01-09 16:15 UTC, marcobottaro approved these changes

2024-01-09 16:25 UTC, merged