[DEV-1252] storybook setup in the same directory
pagopa/developer-portal pull request #546
Opened 2024-01-08 13:22 UTC by tommaso1

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-19 09:01 UTC, MarcoPonchia approved these changes

2024-01-19 09:29 UTC, kin0992 requested changes
Also, check the CI: there are some errors

2024-01-19 09:29 UTC, kin0992 commented on apps/nextjs-website/.storybook/main.ts
> +function getAbsolutePath(value: string): any {
```suggestion
function getAbsolutePath(value: string) {
```

2024-01-19 09:29 UTC, kin0992 commented on apps/nextjs-website/.storybook/main.ts
> + * It is needed in projects that use Yarn PnP or are set up within a monorepo.
According to this comment, we don't need this function, do we?
We are not using `Yarn`

2024-01-19 09:29 UTC, kin0992 commented on package.json
> +    "storybook": "cd ./apps/storybook; npm run storybook",
We should run the command using `turbo`

2024-01-19 09:29 UTC, kin0992 commented on README.md
> +npm run storybook -w nextjs-website
Running this command, the storybook automatically opens in the browser. Can we disable this functionality?

2024-01-25 11:47 UTC, kin0992 requested changes
Still the CI is failing

2024-01-25 11:47 UTC, kin0992 commented on README.md
> +npm run storybook --no-open -w nextjs-website
```suggestion
npm run storybook -w nextjs-website
```
why not putting directly in the script within the `package.json`?

2024-01-25 11:51 UTC, kin0992 commented
And BTW, why should we keep storybook within the `nextjs-website` app and not creating a separate application (e.g. `apps/storybook`?

2024-02-02 08:41 UTC, marcobottaro commented
Converted to draft while looking for an alternative configuration by following previous installation set up

2024-03-15 02:11 UTC, closed without merging