[DEV-1277] Update profile page copy
pagopa/developer-portal pull request #554
Opened 2024-01-10 14:55 UTC by jeremygordillo

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-10 14:58 UTC, kin0992 commented on .changeset/fifty-geese-hammer.md
> +"nextjs-website": minor
Shouldn't be a patch?

2024-01-10 14:59 UTC, kin0992 commented on .changeset/fifty-geese-hammer.md
> +"nextjs-website": minor
If you think this is a patch, then I'd change the "Types of changes" in the PR description to "Bug fix".
Then, please fill the template with missing information.

2024-01-11 16:15 UTC, marcobottaro commented on apps/nextjs-website/src/messages/it.json
>          "hello": "Ciao,",
I think that this is a "ghost" translation string and you should remove it

2024-01-11 16:15 UTC, marcobottaro requested changes
Remove ghost

2024-01-11 16:33 UTC, marcobottaro approved these changes

2024-01-11 16:47 UTC, merged