[DEV-1306] Remove the overlap between the product's menu and the Hero
pagopa/developer-portal pull request #568
Opened 2024-01-19 16:25 UTC by marcobottaro

#### List of Changes

Add a prop to Hero component to add the style that removes the overlap between the product's menu and the Hero

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-19 17:07 UTC, MarcoPonchia requested changes

2024-01-19 17:07 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/[productSlug]/overview/page.tsx
> +        gridTextSx={{ marginTop: { xs: '62px', md: '77px' } }}
I think this `gridTextSx` should also set for api, quickStart, guides and tutorials pages?

2024-01-19 17:15 UTC, MarcoPonchia approved these changes

2024-01-19 17:16 UTC, MarcoPonchia commented on apps/nextjs-website/src/app/[productSlug]/overview/page.tsx
> +        gridTextSx={{ marginTop: { xs: '62px', md: '77px' } }}
My bad i see Hero is only used in overview page

2024-01-19 17:17 UTC, merged

2024-01-22 07:59 UTC, kin0992 commented
@marcobottaro @MarcoPonchia here a changeset would have been nice!