[DEV-1162] Rmove workaround from parse content
pagopa/developer-portal pull request #585
Opened 2024-01-29 11:55 UTC by tommaso1

#### List of Changes

Remove old workaround and parses <p> tags as html.

#### Motivation and Context

Having the workaround caused %p to appear on tables

#### How Has This Been Tested?

go to `pago-pa/guides/saci/3.1.0/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/flusso-di-rendicontazione`

#### Screenshots (if appropriate):
![Screenshot 2024-01-29 125537](https://github.com/pagopa/developer-portal/assets/18684459/c75b7d24-da34-4c11-8ccd-828cba441c1d)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-29 15:51 UTC, MarcoPonchia requested changes

2024-01-29 15:51 UTC, MarcoPonchia commented on packages/gitbook-docs/src/parseContent.ts
> +    //    .replaceAll(pR.regex, pR.replace)
```suggestion
```

2024-01-30 15:05 UTC, kin0992 requested changes

2024-01-30 17:41 UTC, MarcoPonchia approved these changes

2024-01-31 08:55 UTC, kin0992 approved these changes

2024-01-31 15:46 UTC, marcobottaro approved these changes

2024-01-31 15:52 UTC, merged