[DEV-1017] - Configure nextjs to manage CMS contents
pagopa/developer-portal pull request #599
Opened 2024-02-01 11:49 UTC by MarcoPonchia

#### List of Changes

Nextjs manage content recovery from CMS

#### Motivation and Context

Nextjs can retrive data from CMS

#### How Has This Been Tested?

Manually user can:
- see static content if `CMS_BASE_PATH` is not present in .env.local
- see CMS content if `CMS_BASE_PATH="http://localhost:1337/api"` is defined in .env.local

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-01 15:22 UTC, marcobottaro requested changes

2024-02-01 15:22 UTC, marcobottaro commented on .changeset/wild-pugs-wash.md
> +"nextjs-website": major
```suggestion
"nextjs-website": minor
```

2024-02-01 15:22 UTC, marcobottaro commented on apps/nextjs-website/src/lib/types/homepageResponseData.ts
> +    }[];
Add a TODO to manage `target` attribute

2024-02-02 08:51 UTC, marcobottaro approved these changes

2024-02-05 11:50 UTC, MarcoPonchia commented
This PR has been converted to draft because a direct comparison is needed to define the refactor together using "fp-ts"

2024-02-07 16:21 UTC, marcobottaro commented on apps/nextjs-website/src/lib/api.ts
> +    'home-page',
```suggestion
    'homepage',
```

2024-02-12 11:57 UTC, MarcoPonchia commented
This task has been refactor and polished here: https://github.com/pagopa/developer-portal/pull/615

2024-02-12 11:57 UTC, closed without merging