[DEV-1278]: uniform footer
pagopa/developer-portal pull request #606
Opened 2024-02-06 14:20 UTC by MikeAtUqido

#### List of Changes

* Uniform footer as per PagoPA's design

#### Motivation and Context

The footer was different from other PagoPA products

#### How Has This Been Tested?

- [x] Manually

#### Screenshots (if appropriate):
<img width="1728" alt="Screenshot 2024-02-06 alle 15 18 54" src="https://github.com/pagopa/developer-portal/assets/146933303/1408c11f-7f0b-4281-8ddd-103421c71a38">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-06 14:41 UTC, kin0992 commented on apps/nextjs-website/src/components/atoms/IconWrapper/Medium.tsx
Is it possible to use the [`Medium` icon coming from MUI-Italia](https://main--633c31eff9fe385398ada426.chromatic.com/?path=/docs/assets-icons--docs)?

2024-02-06 14:51 UTC, MikeAtUqido commented on apps/nextjs-website/src/components/atoms/IconWrapper/Medium.tsx
I searched for it everywhere and I didn't find it, thanks

2024-02-07 13:09 UTC, marcobottaro requested changes
![screenshot-localhost_3000-2024 02 07-14_07_36](https://github.com/pagopa/developer-portal/assets/39835990/94dc0705-5107-4080-8a4a-76cae5139f63)

Take a look at the footer on mobile

2024-02-08 12:32 UTC, tommaso1 approved these changes

2024-02-09 11:36 UTC, marcobottaro approved these changes

2024-02-09 14:48 UTC, merged