[DEV-1356] - add dns record for CMS Strapi
pagopa/developer-portal pull request #638
Opened 2024-02-13 20:24 UTC by maurodandrea

add dns record for CMS Strapi
Depends on #636 636

#### List of Changes
add dns record for CMS Strapi

#### Motivation and Context
add dns record for CMS Strapi

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My change not requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-14 10:19 UTC, kin0992 commented on .infrastructure/10_dns.tf
> +module "records" {
```suggestion
module "cms_dns_records" {
```
or, if you have a better name, feel free to propose it

2024-02-15 15:34 UTC, kin0992 requested changes

2024-02-15 15:34 UTC, kin0992 commented on .infrastructure/10_dns.tf
> +  zone_id = module.dns_zone_cms.route53_zone_zone_id[keys(var.dns_domain_name_cms)[0]]
```suggestion
  zone_id = aws_route53_zone.dev_portal.id
```
you should use the `dev_portal` zone

2024-02-15 15:34 UTC, kin0992 commented on .infrastructure/10_dns.tf
> +  depends_on = [module.dns_zone_cms]
```suggestion
```
this is not required anymore

2024-02-27 11:35 UTC, datalek approved these changes

2024-02-27 11:35 UTC, kin0992 approved these changes

2024-02-27 11:37 UTC, datalek commented on .infrastructure/dns.tf
> +      name = ""
```suggestion
      name = "cms"
```

2024-02-27 11:37 UTC, datalek commented on .infrastructure/dns.tf
> +      name = "www"
```suggestion
      name = "www.cms"
```

2024-02-27 11:39 UTC, datalek requested changes

2024-02-27 11:39 UTC, datalek commented on .infrastructure/dns.tf
> +    }
```suggestion
    }
```

2024-02-27 11:45 UTC, kin0992 approved these changes

2024-02-27 11:47 UTC, datalek approved these changes

2024-02-27 11:49 UTC, merged