[DEV-1342] Remove email in url
pagopa/developer-portal pull request #663
Opened 2024-02-20 15:49 UTC by tommaso1

#### List of Changes

Remove email from url

#### Motivation and Context

#### How Has This Been Tested?

Register a new user, check the email does not appear on url

#### Screenshots (if appropriate):
![Screenshot 2024-02-20 164118](https://github.com/pagopa/developer-portal/assets/18684459/5df08158-845f-4ef2-9075-60942668d924)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-22 18:04 UTC, marcobottaro commented on apps/nextjs-website/src/app/auth/sign-up/page.tsx
> +    router.replace(`/auth/sign-up?step=${SignUpSteps.CONFIRM_SIGN_UP}`);
Isn't it enough to `setSignUpStep(SignUpSteps.CONFIRM_SIGN_UP);`. Is the route persistent if the user refreshes the page?

2024-02-27 08:49 UTC, marcobottaro commented on apps/nextjs-website/src/app/auth/sign-up/page.tsx
> +    router.replace(`/auth/sign-up?step=${SignUpSteps.CONFIRM_SIGN_UP}`);
ok

2024-02-27 08:49 UTC, marcobottaro approved these changes

2024-02-27 09:32 UTC, kin0992 commented
@tommaso1 add the changeset

2024-02-28 11:05 UTC, marcobottaro requested changes

2024-02-29 15:26 UTC, marcobottaro approved these changes

2024-03-01 11:42 UTC, merged