[DEV-1466] Reset login code form errors on user changes
pagopa/developer-portal pull request #694
Opened 2024-02-29 15:21 UTC by jeremygordillo

#### List of Changes

- Refactor submit function
- Add login form tests

#### Motivation and Context

Reset errors of login confirm code form when user updates invalid input values

#### How Has This Been Tested?

Run ```npm run test -w nextjs-website```

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-06 15:27 UTC, tommaso1 requested changes

2024-03-06 15:27 UTC, tommaso1 commented on apps/nextjs-website/src/components/organisms/Auth/__tests__/ConfirmLogin.test.tsx
> +  const mockOnConfirmLogin = jest.fn(() => Promise.resolve());
Can we use async function instead of manually resolving promises?

2024-03-06 15:27 UTC, tommaso1 commented on apps/nextjs-website/src/components/organisms/Auth/__tests__/ConfirmLogin.test.tsx
> +  const mockResendCode = jest.fn(() => Promise.resolve(true));
same here

2024-03-08 17:40 UTC, marcobottaro requested changes

2024-03-08 17:40 UTC, marcobottaro commented on .changeset/wet-squids-raise.md
> +[DEV-1466] Reset login code form errors on user changes
```suggestion
Reset login code form errors on user changes
```

2024-03-11 14:00 UTC, tommaso1 approved these changes

2024-03-19 15:51 UTC, tommaso1 requested changes

2024-03-19 15:51 UTC, tommaso1 commented on apps/nextjs-website/src/components/organisms/Auth/ConfirmLogin.tsx
> +                onChange={handleChangeCode}
i would call this `handleCodeChanged`

2024-03-21 14:30 UTC, marcobottaro approved these changes

2024-03-25 14:49 UTC, MarcoPonchia approved these changes

2024-03-25 16:24 UTC, tommaso1 approved these changes

2024-03-26 08:47 UTC, merged