[DEV-1393] Handle data-size image attribute to support inline image rendering
pagopa/developer-portal pull request #705
Opened 2024-03-05 17:05 UTC by tommaso1

#### List of Changes

Handle  data-size image attribute to support inline image rendering

#### Motivation and Context

https://pagopa.atlassian.net/browse/DEV-1393

#### How Has This Been Tested?

Go to `/app-io/guides/supporto-agli-enti/v1.0/messaggi/domande-e-risposte-sui-messaggi`  
Check images are shown in a new line.

This also caused a possible regression on DEV-1090, so it was handled to allow all values of `data-size` .
To check there's no regression go to

`/pago-pa/guides/sanp/3.5.0/specifiche-attuative-del-nodo-dei-pagamenti-spc/funzionamento-generale/processi-di-pagamento`

and check the IO logo is still inline. 

go to: 
`/firma-con-io/guides/manuale-operativo/creare-il-dossier`

and check the image is rendered the same as 
`https://docs.pagopa.it/manuale-operativo-di-firma-con-io/creare-il-dossier`

#### Screenshots (if appropriate):
![Screenshot 2024-03-05 175714](https://github.com/pagopa/developer-portal/assets/18684459/8d0b992d-0ebb-414c-8822-e2388fe3a078)
![Screenshot 2024-03-05 175703](https://github.com/pagopa/developer-portal/assets/18684459/e814e22d-f0ae-4bd8-86d3-8a5f488a8dfb)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-06 13:35 UTC, marcobottaro requested changes

2024-03-06 13:35 UTC, marcobottaro commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +    const content = '<img src="img-src.jpg" alt="anAlt" data-size="inline">';
```suggestion
    const content = '<img src="img-src.jpg" alt="anAlt" data-size="line">';
```

2024-03-06 13:35 UTC, marcobottaro commented on packages/gitbook-docs/src/__tests__/parseContent.test.ts
> +        'data-size': 'inline',
```suggestion
        'data-size': 'line',
```

2024-03-07 13:26 UTC, MikeAtUqido approved these changes

2024-03-08 13:53 UTC, datalek approved these changes

2024-03-08 16:28 UTC, marcobottaro approved these changes

2024-03-08 16:40 UTC, merged