[DEV-1481]: webinar link visibility
pagopa/developer-portal pull request #707
Opened 2024-03-07 10:13 UTC by MikeAtUqido

#### List of Changes

* Make webinar link visible in production environment

#### Motivation and Context

The webinar link was not being displayed in production environment

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-07 10:32 UTC, kin0992 requested changes

2024-03-07 10:32 UTC, kin0992 commented on apps/nextjs-website/src/components/molecules/DesktopSiteHeader/DesktopSiteHeader.tsx
Remove the unused import

2024-03-07 10:32 UTC, kin0992 commented on apps/nextjs-website/src/components/molecules/MobileSiteHeader/MobileSiteHeader.tsx
Remove the unused import

2024-03-07 10:32 UTC, kin0992 commented on .changeset/eight-paws-impress.md
> +"nextjs-website": patch
```suggestion
"nextjs-website": minor
```

2024-03-08 13:52 UTC, kin0992 approved these changes

2024-03-08 15:59 UTC, marcobottaro approved these changes

2024-03-08 16:10 UTC, merged