[DEV-1252]: POC -  install storybook custom app
pagopa/developer-portal pull request #719
Opened 2024-03-11 09:18 UTC by MikeAtUqido

#### List of Changes

This PR aims to install a custom Storybook [Storybook](https://storybook.js.org/) app that will render all of the Storyboook's stories defined in the project

#### Motivation and Context

The team already installed the Storybook globally some time ago, this PR restores that functionality moving it in a custom app

#### How Has This Been Tested?

Manually by running Storybook locally

#### Screenshots (if appropriate):
![Atoms-AlertPart-Showcase-⋅-Storybook (1)](https://github.com/pagopa/developer-portal/assets/146933303/4dd9e6b3-d8a0-4ab2-8243-fd782ce9dff4)
![Atoms-CopyToClipboard-Showcase-⋅-Storybook (1)](https://github.com/pagopa/developer-portal/assets/146933303/bc02650f-ecde-4eb5-8df5-bc941be10de4)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-02 15:35 UTC, MarcoPonchia approved these changes

2024-05-03 07:31 UTC, kin0992 commented on apps/nextjs-website/src/components/atoms/AlertPart/AlertPart.stories.tsx
**question**: why the `.stories` files are inside the `nextjs-website` application?

since storybook is a separate application (`apps/storybook-app`), shouldn't be the `.stories` files located under that application?

2024-05-03 09:11 UTC, MikeAtUqido commented on apps/nextjs-website/src/components/atoms/AlertPart/AlertPart.stories.tsx
I moved the `.stories` file into the `storybook-app` appplication as it makes more sense

2024-05-03 09:31 UTC, tommaso1 approved these changes

2024-05-03 09:44 UTC, kin0992 requested changes
**chore**: @MikeAtUqido please update CODEOWNERS file, adding yourself, and who you think should be owner of `storybook-app`.

2024-05-03 09:44 UTC, kin0992 commented on .changeset/serious-dancers-whisper.md
> +"nextjs-website": patch
**suggestion**: remove the `nextjs-website`

there are no changes on that application, so the changeset for that can be removed

2024-05-03 10:03 UTC, kin0992 approved these changes
My approval is related to the `CODEOWNERS` file only.

2024-05-08 08:19 UTC, marcobottaro requested changes

2024-05-08 13:53 UTC, marcobottaro commented on apps/storybook-app/stories/atoms/CtaCard.stories.tsx
> +
```suggestion
```

2024-05-08 14:43 UTC, marcobottaro approved these changes

2024-05-08 14:49 UTC, merged