[DEV-1469] Reset signup form errors on user changes
pagopa/developer-portal pull request #724
Opened 2024-03-11 14:17 UTC by jeremygordillo

#### List of Changes

- refactor signup page & form

#### Motivation and Context

Reset errors of signup form when user updates invalid input values

#### How Has This Been Tested?

Run `npm run test -w nextjs-website`

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-12 12:15 UTC, marcobottaro requested changes

2024-03-12 12:15 UTC, marcobottaro commented on apps/nextjs-website/src/app/auth/sign-up/page.tsx
> +        }
```suggestion
        setUserAlreadyExist(error.code === 'UsernameExistsException')
```

2024-03-12 12:15 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/Auth/Policy.tsx
We should find a more meaningful name

2024-03-12 13:52 UTC, jeremygordillo commented on apps/nextjs-website/src/components/organisms/Auth/Policy.tsx
What do you suggest?

2024-03-19 15:49 UTC, tommaso1 approved these changes

2024-03-21 14:49 UTC, marcobottaro requested changes
There's a problem with the checkbox at the bottom of the page, take a look at the video:
[screencast-localhost_3000-2024.03.21-15_45_58.webm](https://github.com/pagopa/developer-portal/assets/39835990/dcfd60b3-1f59-4567-9635-970d6898a925)

2024-03-21 14:49 UTC, marcobottaro commented on apps/nextjs-website/src/helpers/auth.helpers.ts
> +export const generateSignUpData = (userData: SignUpUserData) => ({
:+1:

2024-03-25 09:47 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/Auth/Policy.tsx
@jeremygordillo something like `PolicyParagraph`

2024-03-25 09:47 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/Auth/Policy.tsx
@MarcoPonchia any suggestion?

2024-03-26 10:05 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/organisms/Auth/Policy.tsx
Maybe  `PoliciesParagraph` because contains both privacy policy and terms of service :thinking:

2024-03-26 12:22 UTC, tommaso1 requested changes

2024-03-26 12:22 UTC, tommaso1 commented on .changeset/large-planes-act.md
> +Reset signup form errors on user changes
```suggestion
Reset signup form errors if user updates form
```

2024-03-26 12:22 UTC, tommaso1 commented on apps/nextjs-website/src/components/organisms/Auth/PasswordTextField.tsx
> +  const endAdornment = (
This is calculated every rerender, it should be put in a dedicated component or memoized
```suggestion
  const endAdornment = useMemo ( () => (
      <InputAdornment position='end'>
      <IconButton
        aria-label='toggle password visibility'
        onClick={handleClickShowPassword}
        onMouseDown={handleMouseDownPassword}
        edge='end'
      >
        {showPassword ? <VisibilityOff /> : <Visibility />}
      </IconButton>
    </InputAdornment>), [showPassword, handleClickShowPassword, handleMouseDownPassword ])
```

2024-03-27 10:13 UTC, marcobottaro approved these changes

2024-03-27 10:26 UTC, tommaso1 approved these changes

2024-03-27 10:42 UTC, merged