[DEV-1505] Webinar tests
pagopa/developer-portal pull request #729
Opened 2024-03-11 15:54 UTC by tommaso1

#### List of Changes

This will add the possibility to add test webinar to the application, test webinars are not visible in homepage
and not visible in webinar index page, must be accessed by direct link
#### Motivation and Context

#### How Has This Been Tested?

go to `/webinars/test`

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-11 16:36 UTC, marcobottaro requested changes

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +    slug: 'test-3',
```suggestion
    slug: 'always-live',
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +    slug: 'test-2',
```suggestion
    slug: 'test-2024-03-13',
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +  slug: 'test',
```suggestion
  slug: 'test-2024-03-14',
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +  title: 'PagoPA LAB - Test Webinar',
```suggestion
  title: 'Test Webinar',
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +      name: 'I modelli dei servizi più frequenti: Multe per violazione codice della strada',
```suggestion
      path: `#`,
      name: 'Lorem ipsum dolor sit amet',
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +    isVisibleInWebinars: true,
Have you considered calling it `isVisibleInWebinarListPage` or `isVisibleInList`?
```suggestion
    isVisibleInList: true,
```

2024-03-11 16:36 UTC, marcobottaro commented on apps/nextjs-website/src/app/webinars/page.tsx
> +  const webinars = await getVisibleInWebinarsWebinars();
This would become
```suggestion
  const webinars = await getVisibleInListWebinars();
```

2024-03-11 16:36 UTC, marcobottaro commented on .changeset/eight-cobras-argue.md
> +Add test events on webinars
```suggestion
Add test events on webinars and isVisibleInList flag to hide them
```

2024-03-11 16:58 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +  playerSrc: 'https://vimeo.com/event/4135276/embed',
Waiting for the correct URL

2024-03-12 09:00 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +    endDateTime: '2024-03-13T14:00:00.000Z',
```suggestion
    endDateTime: '2024-03-13T14:00:00.000Z',
    playerSrc: 'https://vimeo.com/event/4153381/embed',
```

2024-03-12 09:00 UTC, marcobottaro commented on apps/nextjs-website/src/_contents/webinars.ts
> +    endDateTime: '2040-03-13T14:00:00.000Z',
```suggestion
    endDateTime: '2040-03-13T14:00:00.000Z',
    playerSrc: 'https://vimeo.com/event/4153381/embed',
```

2024-03-12 14:15 UTC, marcobottaro approved these changes

2024-03-13 10:32 UTC, datalek approved these changes

2024-03-13 10:38 UTC, merged