[DEV-1495] Reset change password form errors on user changes
pagopa/developer-portal pull request #736
Opened 2024-03-12 15:28 UTC by jeremygordillo

#### List of Changes

- refactor change password page (forgot psw) & form

#### Motivation and Context

Reset errors of change password form when user updates invalid input values

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-21 15:05 UTC, marcobottaro requested changes

2024-03-21 15:05 UTC, marcobottaro commented on apps/nextjs-website/src/app/auth/change-password/page.tsx
> +  const onChangePassword = useCallback(
Maybe you should rename this const to `onPasswordChanged` (I think it's similar to this [comment](https://github.com/pagopa/developer-portal/pull/694/files/368ed67f1feaeef2c613a347a1a95fd86ad0752a#r1530656419))

2024-03-21 15:05 UTC, marcobottaro commented on apps/nextjs-website/src/components/organisms/Auth/ChangePasswordForm.tsx
> +  const handleChange = (ev: ChangeEvent<HTMLInputElement>) => {
Are you handling password change?

2024-03-26 09:14 UTC, marcobottaro approved these changes

2024-03-26 12:25 UTC, tommaso1 approved these changes

2024-03-27 09:19 UTC, merged