[DEV-1502] Add metadata to webinar page
pagopa/developer-portal pull request #738
Opened 2024-03-12 19:27 UTC by tommaso1

#### List of Changes

Add metadata to webinar detail page

#### Motivation and Context

#### How Has This Been Tested?

Go to `/webinars/PagoPA-multe`, check the meta tags

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-13 21:23 UTC, marcobottaro requested changes

2024-03-13 21:23 UTC, marcobottaro commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +    locale: 'it_IT',
The image is missing

2024-03-14 17:19 UTC, marcobottaro submitted a review, later dismissed

2024-03-15 16:43 UTC, tommaso1 commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +    title: 'PagoPA',
It makes sense to me, but the task specifies this very value to be put in the title

2024-03-19 11:11 UTC, kin0992 commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +    title: 'PagoPA',
@tommaso1 take a look at [this comment on Jira](https://pagopa.atlassian.net/browse/DEV-1502?focusedCommentId=131637)

Then, could you update this PR adding useful values to the metadata?

2024-03-20 10:26 UTC, marcobottaro commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +    title: 'PagoPA',
It should be `webinar.title`

2024-03-21 12:00 UTC, marcobottaro requested changes
Fix makeMetadata's title

2024-03-25 09:35 UTC, marcobottaro commented on apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
> +    title: 'PagoPA',
@kin0992 I think that this conversation can be resolved now. Other useful metadata values will be managed with Strapi once the webinars are moved to the CMS

2024-03-25 12:57 UTC, merged