[DEV-1478] Adds new Speaker at PagoPA LAB Webinar
pagopa/developer-portal pull request #744
Opened 2024-03-13 15:37 UTC by certevol

#### List of Changes

#### Motivation and Context

There is a new Speaker

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-13 16:10 UTC, kin0992 approved these changes

2024-03-14 08:26 UTC, marcobottaro requested changes

2024-03-14 08:26 UTC, marcobottaro commented on .changeset/shaggy-eagles-poke.md
> +[DEV-1478] Adds new Speaker at PagoPA LAB Webinar
```suggestion
Add new Speaker to the PagoPA LAB Webinar
```

2024-03-14 09:26 UTC, marcobottaro approved these changes

2024-03-14 13:21 UTC, merged