[DEV-1546]: render blocks content
pagopa/developer-portal pull request #773
Opened 2024-03-22 14:23 UTC by MikeAtUqido

This PR depends on #745 

#### List of Changes

Render the Strapi blocks content on the FE

#### Motivation and Context

This changes were made onto the PR #745 but Strapi requires to be deployed before the FE changes

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-25 09:32 UTC, tommaso1 approved these changes

2024-03-26 10:31 UTC, kin0992 approved these changes
`package.json` and `package-lock.json` files LGTM

2024-03-26 14:48 UTC, MarcoPonchia requested changes
I think there are some missing parts in these PR even if i set value correctly in Strapi FE never show theme in slider. I see from original PR commit history some changes are missing here like codec update !

2024-03-26 15:37 UTC, marcobottaro requested changes

2024-03-26 15:37 UTC, marcobottaro commented on apps/nextjs-website/src/components/atoms/CtaSlide/CtaSlide.tsx
I think that, by default, the subhead text color should be the same as the title:
![image](https://github.com/pagopa/developer-portal/assets/39835990/57986949-26e5-42cd-92df-38b055774718)

2024-03-26 16:59 UTC, MarcoPonchia requested changes

2024-03-26 16:59 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/homepage.ts
> +  subhead: t.union([NullToUndefinedCodec, BlocksContentCodec]),
here is missing `subheadColor` present both in Strapi and `CtaSlideProps.tsx`

2024-03-26 16:59 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/strapi/__tests__/homepage.test.ts
> +          subhead: [
Also here in test is missing `subheadColor`

2024-03-27 07:50 UTC, MarcoPonchia approved these changes

2024-03-27 16:57 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/molecules/BlocksRendererClient/BlocksRendererClient.tsx
> +    : palette.primary.contrastText;
```suggestion
  const textColor = color ? palette.primary[color] : palette.text.primary;
```

2024-03-27 17:18 UTC, marcobottaro approved these changes

2024-03-27 17:58 UTC, merged