[DEV-1536] Strapi setup for webinars and webinar authors
pagopa/developer-portal pull request #780
Opened 2024-03-26 08:55 UTC by tommaso1

#### List of Changes

Backend strapi setup for handling webinars. 
Due to the structure of the website the strapi part should be deployed before the next js one. This pr creates the types on strapi side

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-26 13:42 UTC, marcobottaro requested changes

2024-03-26 13:42 UTC, marcobottaro commented on .changeset/ten-poems-shake.md
> +"strapi-cms": patch
I think it's a new non-breaking feature, so `minor`, not `patch`
```suggestion
"strapi-cms": minor
```

2024-03-26 13:42 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar-author/content-types/webinar-author/schema.json
> +  "collectionName": "webinar_authors",
Why didn't you call the `speakers` instead of `authors`?

2024-03-26 13:42 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
> +    "vimeo_video_id": {
If we use the `id` the editor will be forced to always use Vimeo player and we need to hardcode the path in the FE. What about using the more generic `playerSrc`?

2024-03-26 16:10 UTC, MarcoPonchia approved these changes

2024-03-26 21:10 UTC, marcobottaro requested changes

2024-03-26 21:10 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar-speaker/content-types/webinar-speaker/schema.json
In the front end type `name` and `jobTitle` attributes are required, I think you should consider adding such a characteristic also on the back end side

2024-03-26 21:10 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
Same here for `description`, `title`, `slug`, `isVisibleInHome`, `isVisibleInList`, `imagePath` (coverImage)

2024-03-27 09:27 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
Attribute `isVisibleInHome` was purposely not added in Strapi because will be removed once [this task](https://pagopa.atlassian.net/browse/DEV-1524) and manage using proper relation between homepage and webinars.

2024-03-27 10:20 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
You are right, my mistake!

2024-03-27 10:22 UTC, marcobottaro approved these changes

2024-03-27 10:22 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
> +      "regex": "^[a-zA-Z0-9-]+$"
:+1:

2024-03-27 11:10 UTC, kin0992 commented on apps/strapi-cms/src/api/webinar-speaker/content-types/webinar-speaker/schema.json
> +        "audios"
are all of these types necessary for an avatar?

2024-03-27 11:10 UTC, kin0992 commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
> +      ],
since the property is called `coverImage`, do you think should we handle all these types?

2024-03-27 12:29 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
> +        "audios"
```suggestion
        "images"
```

2024-03-27 14:32 UTC, marcobottaro approved these changes

2024-03-27 15:43 UTC, kin0992 approved these changes

2024-03-27 15:43 UTC, merged