[DEV-1261] Add quickstart guide strapi side
pagopa/developer-portal pull request #842
Opened 2024-04-26 12:14 UTC by tommaso1

#### List of Changes

Add quickstart guides and quickstart guide items strapi side

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

QuickstartGuide:
![image](https://github.com/pagopa/developer-portal/assets/39835990/33cedef7-3ddf-4033-b262-2a9d3188b060)
![image](https://github.com/pagopa/developer-portal/assets/39835990/7e67e394-6391-4ec1-940d-d64df639f2e8)

QuickstartGuideItem:
![image](https://github.com/pagopa/developer-portal/assets/39835990/084c0d97-2b75-4e0b-bc2d-5ca38b34aefa)
![image](https://github.com/pagopa/developer-portal/assets/39835990/feaa3254-e1c7-4a1a-8bae-777d50eb1b3a)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-02 14:22 UTC, MarcoPonchia requested changes

2024-05-02 14:22 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/tutorial/content-types/tutorial/schema.json
i think this file belong to another PR

2024-05-02 14:22 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/tutorial/controllers/tutorial.ts
same here

2024-05-02 14:22 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/tutorial/routes/tutorial.ts
same here

2024-05-02 14:22 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/tutorial/services/tutorial.ts
same here

2024-05-02 14:22 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/quickstart-guide-item/content-types/quickstart-guide-item/schema.json
> +    }
Some attribute are missing and i think `content` should be more complex in NextJS `QuickStartGuide` type manage multiple steps `apps/nextjs-website/src/lib/types/step.ts` and in each step can show different types of bloc `apps/nextjs-website/src/lib/types/part.ts`

2024-05-16 13:20 UTC, marcobottaro requested changes

2024-05-29 09:59 UTC, MarcoPonchia approved these changes

2024-05-29 10:06 UTC, marcobottaro approved these changes

2024-05-29 10:12 UTC, merged