submodule poc
pagopa/developer-portal pull request #843
Opened 2024-05-02 12:08 UTC by tommaso1

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-08 13:13 UTC, marcobottaro commented on apps/nextjs-website/package.json
> +    "update-docs": "git submodule init && git submodule update && cd docs && git checkout docs/from-gitbook && git pull",
You should move this commands into a shell script and use the temporary folder to `move` only `docs` subfolder in `apps/nextjs-website/docs/`. Right now with this script you create the nested subfolder `docs/docs` and the parser cannot access the manuals correctly.

2024-05-29 08:03 UTC, MarcoPonchia requested changes

2024-05-29 08:03 UTC, MarcoPonchia commented on .gitignore
>  apps/nextjs-website/.tmp/
I think docs folder shouldn't be pushed to repository and is correct to be ignored or there is something i have missed ? :thinking: 
```suggestion
apps/nextjs-website/.tmp/
apps/nextjs-website/docs/
```

2024-05-29 12:33 UTC, marcobottaro requested changes
You should add the changeset file

2024-06-05 10:13 UTC, marcobottaro requested changes

2024-06-05 10:13 UTC, marcobottaro commented on apps/nextjs-website/scripts/fetch-local-docs.sh
> +cp -r docs/* .
```suggestion
mv docs/* .
rm -R docs/

```

2024-06-06 10:53 UTC, marcobottaro approved these changes

2024-06-06 11:07 UTC, marcobottaro requested changes

2024-06-06 11:07 UTC, marcobottaro commented on README.md
> +`npm run update-docs -w nextjs-website`
You didn't add the two options. If a developer runs the commands in the order written in the README file, they will download a gigabyte of data and then delete it

2024-06-06 13:04 UTC, marcobottaro approved these changes

2024-06-06 13:12 UTC, MarcoPonchia approved these changes

2024-06-06 15:28 UTC, christian-calabrese approved these changes
LGTM

2024-06-06 15:33 UTC, merged