[DEV-1631] Add slug custom uniq validator
pagopa/developer-portal pull request #851
Opened 2024-05-09 10:23 UTC by MarcoPonchia

#### List of Changes

Add slug custom uniq validator

#### Motivation and Context

Webinars must have a unique slug for the same language in Strapi to be correctly fetch in NextJS once multilingual will be supported

#### How Has This Been Tested?

Editor see an error if try to create or update webinar if slug already exist for another webinar in same language

#### Screenshots (if appropriate):
![image](https://github.com/pagopa/developer-portal/assets/24475319/1ff98ad8-293b-491c-9fcf-6fb5b2a4643c)

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-10 08:12 UTC, marcobottaro requested changes

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +    throw new errors.ApplicationError("End date must be after start date");
```suggestion
    throw new errors.ApplicationError('End date must be after start date');
```

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +import { errors } from "@strapi/utils";
```suggestion
import { errors } from '@strapi/utils';
```

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +      .service("api::webinar.webinar")
```suggestion
      .service('api::webinar.webinar')
```

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +    return webinar?.locale || "it";
```suggestion
    return webinar?.locale || 'it';
```

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +    .query("api::webinar.webinar")
```suggestion
    .query('api::webinar.webinar')
```

2024-05-10 08:12 UTC, marcobottaro commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
> +      "Webinar with the same slug already exists for the current locale"
```suggestion
      'A Webinar with the same slug already exists for the current locale'
```

2024-05-10 09:22 UTC, marcobottaro commented
I see the following error when trying to publish a Webinar:
```error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [t0.id] query: where `t0`.`id` = ?
Error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [t0.id] query: where `t0`.`id` = ?
    at QueryCompiler_SQLite3.toSQL (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:112:13)
    at compileCallback (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/formatter/formatterUtils.js:13:19)
    at rawOrFn (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/formatter/wrappingFormatter.js:225:7)
    at QueryCompiler_SQLite3.whereWrapped (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:1095:17)
    at QueryCompiler_SQLite3.where (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:584:34)
    at /home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:135:40
    at Array.forEach (<anonymous>)
    at QueryCompiler_SQLite3.select (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:134:16)
    at QueryCompiler_SQLite3.toSQL (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querycompiler.js:75:29)
    at QueryBuilder_SQLite3.toSQL (/home/marco/Projects/pagoPA/backend/developer-portal/node_modules/knex/lib/query/querybuilder.js:84:44)```

2024-05-13 09:36 UTC, MarcoPonchia commented on apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
Adding more specific rules would result in having almost double the lines in this file and would make it difficult to read. I preferred to solve [this task](https://pagopa.atlassian.net/jira/software/projects/DEV/boards/280/backlog?selectedIssue=DEV-1594&text=lint) and make this PR depend on [this one](https://github.com/pagopa/developer-portal/pull/857), where I added a specific eslint configuration for Strapi.

2024-05-13 16:22 UTC, marcobottaro commented
LGTM :+1:

2024-05-13 16:22 UTC, marcobottaro approved these changes

2024-05-22 08:27 UTC, merged