[DEV-1617]: move webinars subscriptions to DynamoDB
pagopa/developer-portal pull request #855
Opened 2024-05-13 06:49 UTC by MikeAtUqido

#### List of Changes

* Move webinars subscriptions to Dynamo DB

#### Motivation and Context

We used to store the webinars subscriptions directly in the user attributes, but this object has a maximum length

#### How Has This Been Tested?

- [x] Manually
- [ ] Unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-14 15:48 UTC, MarcoPonchia commented on apps/nextjs-website/src/lib/webinars/__tests__/webinarSubscriptions.test.ts
> +    it('should return error if send returns an error', async () => {
Nice job to add a test to check error case here :+1:  But why this test is only here for adding a subscription and there are not similar test for delete subscription and get subscriptions cases ' :thinking:

2024-05-14 15:55 UTC, MarcoPonchia commented on apps/nextjs-website/src/helpers/user.helper.ts
> +    run();
There is some particular reason to create `run` function that is only call here in `checkUser` instad of something like this:
```
  const checkUser = useCallback(async () => {
    const user = await Auth.currentAuthenticatedUser().catch(() => {
      setLoading(false);
      setUser(null);
      return null;
    });

    if (!user) {
      return;
    }

    const subscriptions = await getUserWebinarSubscriptions(
      user.attributes.email
    ).catch(() => []);

    setLoading(false);
    setAligned(true);
    setUser({ ...user, webinarSubscriptions: subscriptions });
  }, []);
```

2024-05-15 08:45 UTC, MarcoPonchia commented
There is an issue after the state of loading. As you can see in the video, both in while subscribing and unsubscribing, the loading phase is not managed properly, as you can see when i click on subscribe button correctly change state to loading but before change again in cancel subscription for a moment show subscribe button. (You can see it well using slow 3G).
[Screencast from 15-05-2024 10:25:19.webm](https://github.com/pagopa/developer-portal/assets/24475319/15fedf47-39b6-47ad-a004-a54779f4bba9)

2024-05-15 10:36 UTC, MarcoPonchia approved these changes

2024-05-15 16:11 UTC, tommaso1 approved these changes
I'd rename fetchUserAndSubscriptions, but it can work also as it is, I'm therefore approving it anyway

2024-05-15 16:11 UTC, tommaso1 commented on apps/nextjs-website/src/helpers/user.helper.ts
> +  const checkUser = useCallback(async () => {
i would call this fetchUserAndSubscriptions
```suggestion
  const fetchUserAndSubscriptions = useCallback(async () => {
```

2024-05-15 16:11 UTC, tommaso1 commented on apps/nextjs-website/src/helpers/user.helper.ts
> +    await checkUser();
```suggestion
    await fetchUserAndSubscriptions();
```

2024-05-15 16:11 UTC, tommaso1 commented on apps/nextjs-website/src/helpers/user.helper.ts
> +  }, [checkUser]);
```suggestion
  }, [fetchUserAndSubscriptions]);
```

2024-05-16 14:06 UTC, marcobottaro requested changes

2024-05-16 14:06 UTC, marcobottaro commented on apps/nextjs-website/src/lib/webinars/webinarSubscriptions.ts
> +        // map errors to error and dynamodb item to WebinarQuestion
```suggestion
        // map errors to error and dynamodb item to WebinarSubscription
```

2024-05-16 14:06 UTC, marcobottaro commented on apps/nextjs-website/src/lib/webinars/__tests__/webinarSubscriptions.test.ts
> +    it('should return an empty list if questions are undefined', async () => {
```suggestion
    it('should return an empty list if subscriptions are undefined', async () => {
```

2024-05-16 14:25 UTC, marcobottaro commented
The "Visualizza" button should be clickable

![image](https://github.com/pagopa/developer-portal/assets/39835990/b11ffe81-9630-48fb-96b9-a11efbb9f04c)

2024-05-21 13:21 UTC, marcobottaro approved these changes

2024-05-22 07:32 UTC, merged