[DEV-1618] Import webinar subscriptions to ddb script
pagopa/developer-portal pull request #866
Opened 2024-05-16 14:04 UTC by christian-calabrese

#### List of Changes

Implemented script and tests to allow import of users' webinar subscriptions from Amazon Cognito attributes to DynamoDB.

#### Motivation and Context

Writing to Amazon Cognito user's attributes will be deprecated in favor of DynamoDB for enhanced query capabilities and near to limitless scalability. This script allows to import existing subscriptions from Cognito to DynamoDB.

#### How Has This Been Tested?

The script has been tested via unit tests. Moreover, it has been run several times writing to a local dynamodb container and to the development account DynamoDB table.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-17 09:59 UTC, tommaso1 requested changes
Ok to me, it's just missing the changeset

2024-05-17 10:02 UTC, christian-calabrese commented
> Ok to me, it's just missing the changeset

Thank you @tommaso1!
I thought about creating a changeset or not. However, since it's not an actual change to the software and I couldn't find a module to locate it to, I didn't create it.

What do you think?

2024-05-17 10:19 UTC, tommaso1 commented
I would put it on the general webside project, just to track on release that we developed this script, but I get your point

2024-05-17 10:19 UTC, tommaso1 approved these changes

2024-05-20 12:14 UTC, christian-calabrese commented on scripts/webinar-subscriptions-import/src/README.md
> +```pip3 install -r requirements.txt```
Yes, pip comes with python as the default package installer

2024-05-20 15:40 UTC, datalek approved these changes
My knowledge of Python is a bit rusty, but seems fine to me!

2024-05-20 15:46 UTC, merged