[DEV-1669] Solution Preview Card
pagopa/developer-portal pull request #887
Opened 2024-05-30 13:03 UTC by jeremygordillo

#### List of Changes

- Create `SolutionPreviewCard` component
- Create `SolutionPreviewCard` story on storybook
- Create `NextIntlContext` wrapper to translate labels on storybook stories

#### Motivation and Context

To manage solution preview info

#### How Has This Been Tested?

Run `npm run storybook` and check `SolutionPreviewCard` story

#### Screenshots (if appropriate):
<img width="1458" alt="image" src="https://github.com/pagopa/developer-portal/assets/16854782/c95a4f82-3b0b-42ac-9864-e937bbb56a5e">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-30 16:48 UTC, MarcoPonchia approved these changes

2024-06-03 14:46 UTC, marcobottaro requested changes

2024-06-03 14:46 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/SolutionPreviewCard/SolutionsPreviewCard.tsx
> +            >
```suggestion
            <Typography
              variant='sidenav'
              color={(theme) => theme.palette.action.active}
              sx={{ fontWeight: 700 }}
            >
```

2024-06-03 15:00 UTC, marcobottaro approved these changes

2024-06-03 15:14 UTC, marcobottaro approved these changes

2024-06-03 15:14 UTC, merged