[DEV-1670] SolutionStep component
pagopa/developer-portal pull request #888
Opened 2024-05-30 13:08 UTC by jeremygordillo

#### List of Changes

- Create `SolutionStep` component
- Update labels
#### Motivation and Context

#### How Has This Been Tested?

Run `npm run storybook`
#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-30 16:48 UTC, MarcoPonchia approved these changes

2024-06-03 13:05 UTC, marcobottaro approved these changes

2024-06-03 14:43 UTC, marcobottaro requested changes

2024-06-03 14:43 UTC, marcobottaro commented on apps/nextjs-website/src/components/molecules/SolutionStep/SolutionStep.tsx
> +          sx={{ textTransform: 'uppercase' }}
```suggestion
          sx={{ textTransform: 'uppercase', fontWeight: 700 }}
```

2024-06-03 14:54 UTC, merged