[DEV-1671] add stats component
pagopa/developer-portal pull request #896
Opened 2024-06-04 08:08 UTC by MarcoPonchia

#### List of Changes

Add Stats component

#### Motivation and Context

Add Stats component with dark variant

#### How Has This Been Tested?

On Storybook http://localhost:6006/?path=/story/atoms-stats--showcase

#### Screenshots (if appropriate):
![Screenshot from 2024-06-04 10-04-15](https://github.com/pagopa/developer-portal/assets/24475319/2e1d0757-c98d-4554-ae26-f29d57fe29fb)
![Screenshot from 2024-06-04 10-04-23](https://github.com/pagopa/developer-portal/assets/24475319/9b810851-6539-4731-8012-d7d3343f86b5)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-06 08:19 UTC, marcobottaro commented on apps/nextjs-website/src/components/atoms/Stats/Stats.tsx
> +      {items.map(({ title, subtitle, description }, index) => (
Maybe you should use the `EContainer` component

2024-06-07 11:04 UTC, marcobottaro requested changes

2024-06-07 12:03 UTC, MikeAtUqido approved these changes

2024-06-07 12:08 UTC, marcobottaro approved these changes

2024-06-07 12:08 UTC, merged