Add case history page
pagopa/developer-portal pull request #903
Opened 2024-06-06 08:15 UTC by MarcoPonchia

depends on: #889 

#### List of Changes

- Add case histories codec
- Add case histories fetch
- Add case histories page

#### Motivation and Context

User can see Case history

#### How Has This Been Tested?

- [x] Test
- [x] Manually
In order to test this PR you have to create a Case History in strapi then navgigate to  http://localhost:3000/case-histories/{case-history-slug}

#### Screenshots (if app
![screenshot-localhost_3000-2024 06 06-10_03_26](https://github.com/pagopa/developer-portal/assets/24475319/316d9559-ea7a-4eef-bc0f-1bf5823b17f7)
ropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-07 15:24 UTC, tommaso1 approved these changes

2024-06-07 15:38 UTC, marcobottaro requested changes
The changeset is missing

2024-06-11 05:20 UTC, MikeAtUqido approved these changes

2024-06-11 10:44 UTC, marcobottaro approved these changes

2024-06-11 10:49 UTC, merged