[DEV-1661] Homepage strapi refactor
pagopa/developer-portal pull request #909
Opened 2024-06-10 13:09 UTC by MikeAtUqido

#### List of Changes

* Add the new ecosystem section

#### Motivation and Context

With the solutions the homepage needed to be refactored in order to display the new Ecosystem section

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-17 12:51 UTC, marcobottaro requested changes

2024-06-17 12:51 UTC, marcobottaro commented on apps/strapi-cms/src/components/common/ecosysyem.json
There's a typo in the file name `ecosysyem.json`

2024-06-17 12:51 UTC, marcobottaro commented on apps/strapi-cms/src/api/homepage/content-types/homepage/schema.json
> +      "component": "common.ecosysyem"
There's a typo in the component name

2024-06-17 21:18 UTC, tommaso1 approved these changes
Agree with @marcobottaro for the typo, the rest seems ok to me

2024-06-25 13:29 UTC, marcobottaro approved these changes

2024-06-25 14:45 UTC, MarcoPonchia approved these changes

2024-07-09 12:21 UTC, merged