[DEV-1738] Add Api List Page Template
pagopa/developer-portal pull request #927
Opened 2024-06-25 10:25 UTC by MarBert

#### List of Changes

Add ApiListPageTemplate 

#### Motivation and Context

- Adds the template to create the API List page for each product
- Requires [[DEV-1724] [DEV-1701]](https://github.com/pagopa/developer-portal/pull/923)

#### How Has This Been Tested?

With storybook:
http://localhost:6006/?path=/story/templates-apilistpagetemplate--showcase

#### Screenshots (if appropriate):
<img width="446" alt="image" src="https://github.com/pagopa/developer-portal/assets/41899883/c2a5d8d2-ef41-4844-ae79-02a0862c8cfe">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-27 09:34 UTC, MarcoPonchia commented on apps/storybook-app/public/icons/code.svg
There is a reason for having this icon duplicated instead using `apps/nextjs-website/public/icons/code.svg`

2024-06-27 09:56 UTC, marcobottaro commented on apps/storybook-app/public/icons/code.svg
This icon is inside `apps/storybook-app/public/` folder which is now configured to be the directory of Storybook's public assets

2024-07-02 14:15 UTC, MikeAtUqido approved these changes

2024-07-02 16:07 UTC, marcobottaro requested changes

2024-07-02 16:07 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/ApiListPageTemplate/ApiListPageTemplate.tsx
> +      <Box paddingBottom={'80px'}>
```suggestion
      <Box paddingBottom={6}>
```

2024-07-02 22:24 UTC, tommaso1 approved these changes

2024-07-03 11:14 UTC, marcobottaro commented on apps/storybook-app/stories/templates/ApiListPageTemplate.stories.tsx
> +export const Showcase: StoryObj<typeof ApiListPageTemplate> = {
```suggestion
export const Showcase: StoryObj<typeof ApiDataListPageTemplate> = {
```

2024-07-03 11:14 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/ApiListPageTemplate/ApiListPageTemplate.tsx
> +export type ApiListPageTemplateProps = {
```suggestion
export type ApiDataListPageTemplateProps = {
```

2024-07-03 11:15 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/ApiListPageTemplate/ApiListPageTemplate.tsx
> +const ApiListPageTemplate = ({
```suggestion
const ApiDataListPageTemplate = ({
```

2024-07-03 12:45 UTC, MarBert commented on .changeset/rare-files-punch.md
> +Add ApiListPageTemplate to the project
```suggestion
Add ApiDataListPageTemplate to the project
```

2024-07-08 09:28 UTC, marcobottaro requested changes

2024-07-08 09:28 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/ApiDataListPageTemplate/ApiDataListPageTemplate.tsx
> +          cardSize={{ xs: 12, md: 16 / Math.max(cards.length, 3) }}
I don't think that this formula is what we need:
![image](https://github.com/pagopa/developer-portal/assets/39835990/690bf323-43ef-4265-8a6e-31a11f0df119)

2024-07-08 09:28 UTC, marcobottaro commented on apps/nextjs-website/src/components/templates/ApiDataListPageTemplate/ApiDataListPageTemplate.tsx
> +          cardSize={{ xs: 12, md: 16 / Math.max(cards.length, 3) }}
```suggestion
          cardSize={{ xs: 12, md: 4 }}
```

2024-07-10 12:42 UTC, MarcoPonchia approved these changes

2024-07-10 12:43 UTC, marcobottaro approved these changes

2024-07-10 12:52 UTC, merged