Draft: Add pagopa guides
pagopa/developer-portal pull request #93
Opened 2023-06-29 18:19 UTC by marcobottaro

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-03 10:53 UTC, datalek requested changes

2023-07-03 10:53 UTC, datalek commented on apps/nextjs-website/src/_contents/products.ts
>  export const productsGuides = [pagoPaGuides];
The `productsGuides` is going to be ambiguous once the gitbook guides are integrated. What do you think to rename it to `guideHomepages`?

2023-07-03 10:53 UTC, datalek commented on apps/nextjs-website/src/components/atoms/NavigateButton/LinkButton.tsx
> +  title = '',
```suggestion
  href,
  title,
```

2023-07-03 10:53 UTC, datalek commented on apps/nextjs-website/src/lib/api.ts
> +    (overviewData) => overviewData.product?.path === `/${productSlug}`
```suggestion
    (overviewData) => overviewData.product.path === `/${productSlug}`
```

2023-07-03 10:53 UTC, datalek commented on apps/nextjs-website/src/lib/types/guidesData.ts
> +export type GuidesData = Page<Omit<GuidesPageProps, 'products'>>;
The property `products` does not exist
```suggestion
export type GuidesData = Page<GuidesPageProps>;
```

2023-07-03 10:53 UTC, datalek commented on apps/nextjs-website/src/pages/[productSlug]/guides.tsx
> +        </Breadcrumbs>*/}
```suggestion
```

2023-07-03 10:59 UTC, datalek commented on apps/nextjs-website/src/lib/types/guidesData.ts
> +export type GuidesData = Page<Omit<GuidesPageProps, 'products'>>;
Ignore this suggestion. I didn't see that `LayoutProps` has the `products` property.

2023-07-03 11:18 UTC, kin0992 requested changes

2023-07-03 11:18 UTC, kin0992 commented on apps/nextjs-website/src/components/atoms/GuideCard/GuideCard.tsx
I guess this component should be a inside the molecules folder: it imports 2 atoms, so I guess it _cannot be_ an atom. am I right?

2023-07-03 11:18 UTC, kin0992 commented on apps/nextjs-website/src/components/atoms/GuideCard/GuideCard.tsx
> +            <LinkButton {...link}></LinkButton>
```suggestion
            <LinkButton {...link} />
```

2023-07-03 17:33 UTC, marcobottaro commented on apps/nextjs-website/src/components/atoms/GuideCard/GuideCard.tsx
Good point! I moved it

2023-07-04 08:04 UTC, kin0992 reviewed
I think appIO guide index page is missing

2023-07-04 08:16 UTC, kin0992 approved these changes
👍

2023-07-04 08:22 UTC, datalek approved these changes
📖

2023-07-04 08:23 UTC, merged