[CAI-41]: ChatBot FAB
pagopa/developer-portal pull request #946
Opened 2024-07-02 15:32 UTC by Sebastiano-Bertolin

#### List of Changes
Add ChatBot Floating Action Button

#### Motivation and Context

This button will open the chatbot modal to continue or start a new a chat

#### How Has This Been Tested?

It has been tested via Storybook

#### Screenshots (if appropriate):
<img width="520" alt="Screenshot 2024-07-02 at 17 31 22" src="https://github.com/pagopa/developer-portal/assets/56671015/0e83ad09-86a7-406c-8b50-aaeb2dfa8347">
<img width="546" alt="Screenshot 2024-07-02 at 17 31 55" src="https://github.com/pagopa/developer-portal/assets/56671015/f20dd868-33fb-4e42-95f9-9de0651c8ea2">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-02 22:18 UTC, tommaso1 approved these changes

2024-07-04 12:19 UTC, marcobottaro requested changes

2024-07-04 15:00 UTC, Sebastiano-Bertolin commented on apps/nextjs-website/src/components/atoms/ChatButton/ChatButton.tsx
> +  chatOpen,
Done

2024-07-15 09:56 UTC, MarcoPonchia commented on apps/storybook-app/stories/atoms/ChatbotButton.stories.tsx
> +    chatOpen: false,
`chatOpen` args looks like is never used, maybe did  you mean to use `isChatOpen` ? :thinking:

2024-07-15 09:56 UTC, MarcoPonchia commented on apps/storybook-app/stories/atoms/ChatbotButton.stories.tsx
> +    chatOpen: false,
same here

2024-07-15 14:28 UTC, Sebastiano-Bertolin commented on apps/storybook-app/stories/atoms/ChatbotButton.stories.tsx
> +    chatOpen: false,
Fixed

2024-07-17 14:23 UTC, MarcoPonchia approved these changes

2024-07-17 14:34 UTC, marcobottaro commented on .changeset/breezy-bulldogs-vanish.md
> +"storybook-app": patch
```suggestion
"nextjs-website": minor
"storybook-app": minor
```

2024-07-17 15:28 UTC, marcobottaro approved these changes

2024-07-17 15:29 UTC, merged