[CAI-41] Chat component
pagopa/developer-portal pull request #953
Opened 2024-07-03 14:44 UTC by Sebastiano-Bertolin

#### List of Changes
Add Chat component 

#### Motivation and Context
This component is used in the Chatbot modal and contains the messages and input text field

#### How Has This Been Tested?
Tested via Storybook

#### Screenshots (if appropriate):
<img width="1290" alt="Screenshot 2024-07-03 at 16 44 06" src="https://github.com/pagopa/developer-portal/assets/56671015/3fade68e-042d-4cf5-8e9a-b3706d9932b7">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-15 11:06 UTC, MarcoPonchia requested changes

2024-07-15 11:06 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/molecules/Chat/Chat.tsx
> +              <ListItemText>Delete</ListItemText>
This should be translated

2024-07-15 11:06 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/molecules/Chat/Chat.tsx
> +              <ListItemText>Cronologia Chat</ListItemText>
This should be translated

2024-07-15 11:06 UTC, MarcoPonchia commented on apps/nextjs-website/src/components/molecules/Chat/Chat.tsx
> +  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
`handleClick` name isn't very expressive maybe something like `handleChatMenuClick` could be more clear ?

2024-07-18 13:14 UTC, MarcoPonchia commented on .changeset/popular-glasses-love.md
This changeset can be deleted, is already present in this PR https://github.com/pagopa/developer-portal/pull/952/files

2024-07-18 13:24 UTC, MarcoPonchia commented on .changeset/popular-glasses-love.md
Maybe just align branch to main will remove this changeset

2024-07-19 15:28 UTC, Sebastiano-Bertolin commented on .changeset/popular-glasses-love.md
Done

2024-07-22 15:20 UTC, MarcoPonchia requested changes

2024-07-22 15:20 UTC, MarcoPonchia commented on .changeset/popular-glasses-love.md
I think this file should be deleted

2024-07-22 15:23 UTC, MarcoPonchia approved these changes

2024-07-22 15:48 UTC, MarcoPonchia approved these changes

2024-07-22 15:56 UTC, merged