[DEV-1765] Fix incorrect plural from SolutionsListPage on FE
pagopa/developer-portal pull request #985
Opened 2024-07-11 09:12 UTC by MikeAtUqido

#### List of Changes

Fix incorrect plural from SolutionsListPage on FE

#### Motivation and Context

The plural on SolutionsListPage was incorrect

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-11 10:48 UTC, marcobottaro requested changes

2024-07-11 10:48 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/solutionsListCodec.ts
>  export const fetchSolutionsList = fetchFromStrapi(
I think you should also rename this constant and fix singular/plural issue about `solution list` in all of the components and methods of the project

2024-07-11 10:48 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/solutionsListCodec.ts
> -        populate: ['bannerLinks', 'items.icon'],
Well done, solution list doesn't contain any bannerlink!

2024-07-15 12:54 UTC, marcobottaro approved these changes

2024-07-17 14:55 UTC, MarcoPonchia requested changes

2024-07-17 14:55 UTC, MarcoPonchia commented on .changeset/plenty-actors-add.md
> +"nextjs-website": patch
```suggestion
"nextjs-website": major
```

2024-07-18 12:26 UTC, merged