[DEV-1786] Add parts on tutorials on CMS
pagopa/developer-portal pull request #995
Opened 2024-07-15 13:42 UTC by MikeAtUqido

#### List of Changes

Add parts on tutorials on CMS

#### Motivation and Context

The tutorials used `content` but it was missing some implementations

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-15 16:41 UTC, marcobottaro requested changes

2024-07-15 16:41 UTC, marcobottaro commented on apps/strapi-cms/src/api/tutorial/content-types/tutorial/schema.json
> +      ],
```suggestion
      "components": [
        "parts.alert",
        "parts.code-block",
        "parts.embed-html",
        "parts.html",
        "parts.quote"
      ],
```

2024-07-17 08:12 UTC, tommaso1 approved these changes

2024-07-17 16:08 UTC, MarcoPonchia requested changes

2024-07-17 16:08 UTC, MarcoPonchia commented on .changeset/slow-cows-raise.md
> +"strapi-cms": minor
```suggestion
"strapi-cms": major
```

2024-07-18 09:09 UTC, MarcoPonchia approved these changes

2024-07-18 09:18 UTC, marcobottaro approved these changes

2024-07-18 09:20 UTC, merged