[DEV-1787] Add parts on tutorials on FE
pagopa/developer-portal pull request #996
Opened 2024-07-15 13:42 UTC by MikeAtUqido

#### List of Changes

Add parts on tutorials on FE

#### Motivation and Context

The tutorials used `content` but it was missing some implementations

#### How Has This Been Tested?

Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-15 16:31 UTC, marcobottaro requested changes

2024-07-15 16:31 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/tutorial.ts
>    id: t.number,
```
const BannerLinkCodec = t.strict({
  id: t.number,
  title: t.union([NullToUndefinedCodec, t.string]),
  content: t.union([NullToUndefinedCodec, BlocksContentCodec]),
});
```

2024-07-15 16:42 UTC, marcobottaro requested changes

2024-07-15 16:42 UTC, marcobottaro commented on apps/nextjs-website/src/lib/strapi/tutorial.ts
> +        ],
```suggestion
        populate: ['backgroundImage'],
```

2024-07-17 08:29 UTC, tommaso1 approved these changes

2024-07-17 16:20 UTC, MarcoPonchia requested changes

2024-07-17 16:20 UTC, MarcoPonchia commented on .changeset/green-toys-add.md
> +"nextjs-website": minor
```suggestion
"nextjs-website": major
```

2024-07-18 09:09 UTC, MarcoPonchia approved these changes

2024-07-18 09:20 UTC, marcobottaro approved these changes

2024-07-18 09:38 UTC, merged