[DEV-1792] Fix solution Stats layout
pagopa/developer-portal pull request #999
Opened 2024-07-15 14:25 UTC by MarBert

#### List of Changes

Fix the stats tab in the solution page

#### Motivation and Context

The layout is currently different from figma 

#### How Has This Been Tested?

On localhost

#### Screenshots (if appropriate):
<img width="435" alt="image" src="https://github.com/user-attachments/assets/cbd3c787-d891-43d6-9889-926581a10aae">

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-15 14:27 UTC, MarBert commented on apps/nextjs-website/src/components/atoms/Stats/Stats.tsx
>                {subtitle && (
@marcobottaro i notices that on strapi, there is no subtitle for the stats in the solution model, so this part of code is never used

2024-07-16 08:02 UTC, marcobottaro requested changes

2024-07-16 08:02 UTC, marcobottaro commented on apps/nextjs-website/src/components/atoms/Stats/Stats.tsx
```
'use client';
import EContainer from '@/editorialComponents/EContainer/EContainer';
import { Box, Stack, Typography, useTheme } from '@mui/material';
import React from 'react';

type StatItem = {
  title: string;
  description?: string;
};

type StatsProps = {
  items: StatItem[];
  maxWidth?: number;
  useDarkTheme?: boolean;
};

const Stats = ({ items, maxWidth = 150, useDarkTheme = false }: StatsProps) => {
  const { palette } = useTheme();

  const titleColor = useDarkTheme ? palette.common.white : palette.primary.main;
  const textColor = useDarkTheme ? palette.common.white : palette.text.primary;
  const bgColor = useDarkTheme
    ? palette.primary.main
    : palette.background.default;

  return (
    <Box bgcolor={bgColor}>
      <EContainer>
        <Stack
          flexDirection={{ xs: 'column', sm: 'row' }}
          justifyContent={'space-between'}
          alignItems={'center'}
          gap={4}
          paddingTop={{ xs: '2.5rem', sm: '75px' }}
          paddingBottom={{ xs: '2.5rem', sm: '104px' }}
          width={'100%'}
        >
          {items.map(({ title, description }, index) => (
            <Stack
              key={index}
              flex={1}
              flexDirection={'column'}
              textAlign={'center'}
              justifyContent={'start'}
              maxWidth={maxWidth}
            >
              <Typography
                marginBottom={'.7rem'}
                fontSize={50}
                fontWeight={700}
                color={titleColor}
              >
                {title}
              </Typography>
              {description && (
                <Typography
                  color={textColor}
                  fontWeight={600}
                  fontSize={24}
                  lineHeight={1.2}
                >
                  {description}
                </Typography>
              )}
            </Stack>
          ))}
        </Stack>
      </EContainer>
    </Box>
  );
};

export default Stats;
```

2024-07-16 13:52 UTC, marcobottaro requested changes

2024-07-16 13:52 UTC, marcobottaro commented on .changeset/lovely-moles-impress.md
> +"storybook-app": minor
```suggestion
"storybook-app": patch
```

2024-07-16 13:53 UTC, marcobottaro approved these changes

2024-07-17 07:34 UTC, merged